using System;

using Microsoft.Build.Utilities;

using StaticTeamCityBuildEngine.CommonEngines;
using StaticTeamCityBuildEngine.Interfaces;

namespace StaticTeamCityBuildEngine
{
    public class CreateBranchFiles : Task
    {
        private string _sideBySideName;

        public string SideBySideName
        {
            set { _sideBySideName = value; }
        }

        private string _buildNumber;

        public string BuildNumber
        {
            set { _buildNumber = value; }
        }

        private string _lastHash;

        public string LastHash
        {
            set { _lastHash = value; }
        }

        private string _recreateExistingFiles;

        public string RecreateExistingFiles
        {
            set { _recreateExistingFiles = value; }
        }

        public override bool Execute()
        {
            IExternalExecutor externalExecutor = new ExternalExecutor(Log);
            var createBranchFilesEngine = new CreateBranchFilesEngine(Log, externalExecutor, _recreateExistingFiles);

            try
            {
                Log.LogMessage("Start CreateBranchFiles");
                Log.LogMessage("DefaultSideBySideName=" + _sideBySideName);
                Log.LogMessage("BuildNumber=" + _buildNumber);
                Log.LogMessage("LastHash=" + _lastHash);

                if (string.IsNullOrEmpty(_buildNumber))
                {
                    Log.LogError("BuildNumber is empty");
                    throw new Exception("Empty BuildNumber");
                }

                string sideBySideName;
                string lastCommitHash;
                try
                {
                    sideBySideName = createBranchFilesEngine.GetSideBySideName(_sideBySideName);
                    lastCommitHash = createBranchFilesEngine.GetLastCommitHash(_lastHash);
                }
                catch (Exception ex)
                {
                    if (createBranchFilesEngine.IsAutoGeneratedFilesAvailable())
                    {
                        Log.LogMessage("We got an error with git.exe:\r\n" + ex + "\r\nBut autogenerated files are available. Continue build.");
                        return true;
                    }

                    throw;
                }

                Log.LogMessage("sideBySideName=" + sideBySideName);
                Log.LogMessage("lastCommitHash=" + lastCommitHash);

                var globalInfo = new GlobalInfo(sideBySideName, _buildNumber, lastCommitHash);

                createBranchFilesEngine.CreateSideBySideNameFile(sideBySideName);

                createBranchFilesEngine.CreateBranchInfoFile(sideBySideName);

                createBranchFilesEngine.CreateGlobalAssemblyInfo(globalInfo);

                createBranchFilesEngine.CreateDirectoryBuildProps(globalInfo);

                createBranchFilesEngine.CreateCatiBuildNumberFile(globalInfo);

                Log.LogMessage("Finish CreateBranchFiles");
            }
            catch (Exception ex)
            {
                Log.LogMessage(ex.ToString());
                throw;
            }

            return true;
        }
    }
}
