//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IActivityLoggingSettings
    {
		
        /// <summary>
        /// If Interviewer Activity Event takes longer than Threshold time then it will contain timings information, otherwise it will not.
        /// </summary>
        TimeSpan InterviewerActivityEventTimingsThreshold{ get; set; }
		
        /// <summary>
        /// If Management Activity Event takes longer than Threshold time then it will contain timings information, otherwise it will not.
        /// </summary>
        TimeSpan ManagementActivityEventTimingsThreshold{ get; set; }
    }

	public interface IActivityLoggingSettingsGroup : IActivityLoggingSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class ActivityLoggingSettings : IActivityLoggingSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public ActivityLoggingSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// If Interviewer Activity Event takes longer than Threshold time then it will contain timings information, otherwise it will not.
        /// </summary>
        public TimeSpan InterviewerActivityEventTimingsThreshold
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.ActivityLogging.InterviewerActivityEventTimingsThreshold);
                return TimeSpan.Parse( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.ActivityLogging.InterviewerActivityEventTimingsThreshold, value );
            }
        }
		
        /// <summary>
        /// If Management Activity Event takes longer than Threshold time then it will contain timings information, otherwise it will not.
        /// </summary>
        public TimeSpan ManagementActivityEventTimingsThreshold
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.ActivityLogging.ManagementActivityEventTimingsThreshold);
                return TimeSpan.Parse( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.ActivityLogging.ManagementActivityEventTimingsThreshold, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
