//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;
using Confirmit.CATI.Core.SystemSettings.Alerting;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IAlertingSettings
    {
		
		INoCallsSettings NoCalls{ get; }
		
		ISchedulingErrorsSettings SchedulingErrors{ get; }
		
		ISelectingStateSettings SelectingState{ get; }
		
		IWaitingStateSettings WaitingState{ get; }
    }

	public interface IAlertingSettingsGroup : IAlertingSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class AlertingSettings : IAlertingSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;
		
		private readonly INoCallsSettingsGroup _NoCalls;
		
		private readonly ISchedulingErrorsSettingsGroup _SchedulingErrors;
		
		private readonly ISelectingStateSettingsGroup _SelectingState;
		
		private readonly IWaitingStateSettingsGroup _WaitingState;

		public AlertingSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		
			_NoCalls = ServiceLocator.Resolve<INoCallsSettingsGroup>();
		
			_SchedulingErrors = ServiceLocator.Resolve<ISchedulingErrorsSettingsGroup>();
		
			_SelectingState = ServiceLocator.Resolve<ISelectingStateSettingsGroup>();
		
			_WaitingState = ServiceLocator.Resolve<IWaitingStateSettingsGroup>();
		}
		
		public INoCallsSettings NoCalls { get { return _NoCalls; } }
		
		public ISchedulingErrorsSettings SchedulingErrors { get { return _SchedulingErrors; } }
		
		public ISelectingStateSettings SelectingState { get { return _SelectingState; } }
		
		public IWaitingStateSettings WaitingState { get { return _WaitingState; } }

        partial void OnSettingsChanged();

		public void OnChanged()
		{
			_NoCalls.OnChanged();
			_SchedulingErrors.OnChanged();
			_SelectingState.OnChanged();
			_WaitingState.OnChanged();

			OnSettingsChanged();
		}
    }
}
