//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IAppointmentAlertSettings
    {
		
        /// <summary>
        /// Long interval for appointment counters (Appointment List from the Activity Views).
        /// </summary>
        int LongInterval{ get; set; }
		
        /// <summary>
        /// Short interval for appointment counters (Appointment List from the Activity Views).
        /// </summary>
        int ShortInterval{ get; set; }
    }

	public interface IAppointmentAlertSettingsGroup : IAppointmentAlertSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class AppointmentAlertSettings : IAppointmentAlertSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public AppointmentAlertSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Long interval for appointment counters (Appointment List from the Activity Views).
        /// </summary>
        public int LongInterval
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.AppointmentAlert.LongInterval);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.AppointmentAlert.LongInterval, value );
            }
        }
		
        /// <summary>
        /// Short interval for appointment counters (Appointment List from the Activity Views).
        /// </summary>
        public int ShortInterval
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.AppointmentAlert.ShortInterval);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.AppointmentAlert.ShortInterval, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
