//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings.Console
{
    public partial interface IMetricsSettings
    {
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of made appointments in the performance metrics
        /// </summary>
        bool EnableAppointmentsMade{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the average number of call attempts per hour in the performance metrics
        /// </summary>
        bool EnableAverageCallAttemptsPerHour{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the average number of completed interviews per hour in the performance metrics
        /// </summary>
        bool EnableAverageCompletedInterviewsPerHour{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his average connected call time in the performance metrics
        /// </summary>
        bool EnableAverageConnectedCallTime{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his average wrap time in the performance metrics
        /// </summary>
        bool EnableAverageWrapTime{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his total break duration in the performance metrics
        /// </summary>
        bool EnableBreakDuration{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his call attempts count in the performance metrics
        /// </summary>
        bool EnableCallAttempts{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews per complete in the performance metrics
        /// </summary>
        bool EnableCallAttemptsPerComplete{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Above Average tag, indicating that they are making more call attempts per completed interview than the company average
        /// </summary>
        bool EnableCallAttemptsPerCompleteAboveAverageComparison{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Below Average tag, indicating that they are making fewer call attempts per completed interview than the company average
        /// </summary>
        bool EnableCallAttemptsPerCompleteBelowAverageComparison{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews per hour in the performance metrics
        /// </summary>
        bool EnableCallAttemptsPerHour{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Above Average tag, indicating that they are making more call attempts per hour than the company average
        /// </summary>
        bool EnableCallAttemptsPerHourAboveAverageComparison{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Below Average tag, indicating that they are making fewer call attempts per hour than the company average
        /// </summary>
        bool EnableCallAttemptsPerHourBelowAverageComparison{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his call connected time in the performance metrics
        /// </summary>
        bool EnableCallConnectedTime{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his calls connected count in the performance metrics
        /// </summary>
        bool EnableCallsConnected{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to open interviewer performance metrics
        /// </summary>
        bool EnableInterviewerMetrics{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews in the performance metrics
        /// </summary>
        bool EnableInterviewsCompleted{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews per hour in the performance metrics
        /// </summary>
        bool EnableInterviewsCompletedPerHour{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Above Average tag, indicating that they are making more interview completes per hour than the company average
        /// </summary>
        bool EnableInterviewsCompletedPerHourAboveAverageComparison{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Below Average tag, indicating that they are making less interview completes per hour than the company average
        /// </summary>
        bool EnableInterviewsCompletedPerHourBelowAverageComparison{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his login session duration in the performance metrics
        /// </summary>
        bool EnableLoginSessionDuration{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of refused calls in the performance metrics
        /// </summary>
        bool EnableRefusals{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the total number of completed interviews in the performance metrics
        /// </summary>
        bool EnableTotalCompletedInterviews{ get; set; }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the total interviewing time in the performance metrics
        /// </summary>
        bool EnableTotalInterviewingTime{ get; set; }
    }

	public interface IMetricsSettingsGroup : IMetricsSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class MetricsSettings : IMetricsSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public MetricsSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of made appointments in the performance metrics
        /// </summary>
        public bool EnableAppointmentsMade
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableAppointmentsMade);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableAppointmentsMade, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the average number of call attempts per hour in the performance metrics
        /// </summary>
        public bool EnableAverageCallAttemptsPerHour
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableAverageCallAttemptsPerHour);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableAverageCallAttemptsPerHour, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the average number of completed interviews per hour in the performance metrics
        /// </summary>
        public bool EnableAverageCompletedInterviewsPerHour
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableAverageCompletedInterviewsPerHour);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableAverageCompletedInterviewsPerHour, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his average connected call time in the performance metrics
        /// </summary>
        public bool EnableAverageConnectedCallTime
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableAverageConnectedCallTime);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableAverageConnectedCallTime, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his average wrap time in the performance metrics
        /// </summary>
        public bool EnableAverageWrapTime
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableAverageWrapTime);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableAverageWrapTime, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his total break duration in the performance metrics
        /// </summary>
        public bool EnableBreakDuration
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableBreakDuration);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableBreakDuration, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his call attempts count in the performance metrics
        /// </summary>
        public bool EnableCallAttempts
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttempts);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttempts, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews per complete in the performance metrics
        /// </summary>
        public bool EnableCallAttemptsPerComplete
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerComplete);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerComplete, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Above Average tag, indicating that they are making more call attempts per completed interview than the company average
        /// </summary>
        public bool EnableCallAttemptsPerCompleteAboveAverageComparison
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerCompleteAboveAverageComparison);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerCompleteAboveAverageComparison, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Below Average tag, indicating that they are making fewer call attempts per completed interview than the company average
        /// </summary>
        public bool EnableCallAttemptsPerCompleteBelowAverageComparison
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerCompleteBelowAverageComparison);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerCompleteBelowAverageComparison, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews per hour in the performance metrics
        /// </summary>
        public bool EnableCallAttemptsPerHour
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerHour);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerHour, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Above Average tag, indicating that they are making more call attempts per hour than the company average
        /// </summary>
        public bool EnableCallAttemptsPerHourAboveAverageComparison
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerHourAboveAverageComparison);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerHourAboveAverageComparison, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Below Average tag, indicating that they are making fewer call attempts per hour than the company average
        /// </summary>
        public bool EnableCallAttemptsPerHourBelowAverageComparison
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerHourBelowAverageComparison);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallAttemptsPerHourBelowAverageComparison, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his call connected time in the performance metrics
        /// </summary>
        public bool EnableCallConnectedTime
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallConnectedTime);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallConnectedTime, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his calls connected count in the performance metrics
        /// </summary>
        public bool EnableCallsConnected
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableCallsConnected);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableCallsConnected, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to open interviewer performance metrics
        /// </summary>
        public bool EnableInterviewerMetrics
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableInterviewerMetrics);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableInterviewerMetrics, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews in the performance metrics
        /// </summary>
        public bool EnableInterviewsCompleted
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableInterviewsCompleted);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableInterviewsCompleted, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of completed interviews per hour in the performance metrics
        /// </summary>
        public bool EnableInterviewsCompletedPerHour
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableInterviewsCompletedPerHour);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableInterviewsCompletedPerHour, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Above Average tag, indicating that they are making more interview completes per hour than the company average
        /// </summary>
        public bool EnableInterviewsCompletedPerHourAboveAverageComparison
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableInterviewsCompletedPerHourAboveAverageComparison);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableInterviewsCompletedPerHourAboveAverageComparison, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the Below Average tag, indicating that they are making less interview completes per hour than the company average
        /// </summary>
        public bool EnableInterviewsCompletedPerHourBelowAverageComparison
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableInterviewsCompletedPerHourBelowAverageComparison);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableInterviewsCompletedPerHourBelowAverageComparison, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his login session duration in the performance metrics
        /// </summary>
        public bool EnableLoginSessionDuration
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableLoginSessionDuration);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableLoginSessionDuration, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see his count of refused calls in the performance metrics
        /// </summary>
        public bool EnableRefusals
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableRefusals);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableRefusals, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the total number of completed interviews in the performance metrics
        /// </summary>
        public bool EnableTotalCompletedInterviews
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableTotalCompletedInterviews);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableTotalCompletedInterviews, value );
            }
        }
		
        /// <summary>
        /// When enabled, the interviewer will be able to see the total interviewing time in the performance metrics
        /// </summary>
        public bool EnableTotalInterviewingTime
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Console.Metrics.EnableTotalInterviewingTime);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Console.Metrics.EnableTotalInterviewingTime, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
