//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IDebugSettings
    {
		
        /// <summary>
        /// Breakpoint on backend startup
        /// </summary>
        bool BackendStartup{ get; set; }
		
        /// <summary>
        /// Should metadata for external services be published or not. Possible values: True or False
        /// </summary>
        bool PublishMetadataForExternalWCFServices{ get; set; }
		
        /// <summary>
        /// Should metadata for internal services be published or not. Possible values: True or False
        /// </summary>
        bool PublishMetadataForInternalWCFServices{ get; set; }
    }

	public interface IDebugSettingsGroup : IDebugSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class DebugSettings : IDebugSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public DebugSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Breakpoint on backend startup
        /// </summary>
        public bool BackendStartup
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Debug.BackendStartup);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Debug.BackendStartup, value );
            }
        }
		
        /// <summary>
        /// Should metadata for external services be published or not. Possible values: True or False
        /// </summary>
        public bool PublishMetadataForExternalWCFServices
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Debug.PublishMetadataForExternalWCFServices);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Debug.PublishMetadataForExternalWCFServices, value );
            }
        }
		
        /// <summary>
        /// Should metadata for internal services be published or not. Possible values: True or False
        /// </summary>
        public bool PublishMetadataForInternalWCFServices
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Debug.PublishMetadataForInternalWCFServices);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Debug.PublishMetadataForInternalWCFServices, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
