//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IInterviewerPasswordSettings
    {
		
        /// <summary>
        /// CATI interviewer expiration period in days.
        /// </summary>
        int ExpirationPeriodInDays{ get; set; }
		
        /// <summary>
        /// CATI interviewer is required to change his password on the first login
        /// </summary>
        bool IsChangeAfterFirstLoginRequired{ get; set; }
		
        /// <summary>
        /// Is complex password rule enforced for CATI interviewer password. Possible values: true or false. Complex password must must have at least 1 upper case character and 1 non-alphanumeric character.
        /// </summary>
        bool IsComplexPasswordEnforced{ get; set; }
		
        /// <summary>
        /// Is CATI interviewer password expiration enabled. Possible values: true or false.
        /// </summary>
        bool IsExpirationEnabled{ get; set; }
		
        /// <summary>
        /// Minimal allowed length of CATI interviewer password. If 0 then any length is allowed.
        /// </summary>
        bool IsMinimumPasswordLengthEnforced{ get; set; }
		
        /// <summary>
        /// Can CATI interviewer set the same password during password change procedure. Possible values: true or false.
        /// </summary>
        bool IsResetToSamePasswordEnabled{ get; set; }
		
        /// <summary>
        /// Minimal allowed length of CATI interviewer password. This option works only when IsMinimumPasswordLengthEnforced is True.
        /// </summary>
        int MinimumPasswordLength{ get; set; }
    }

	public interface IInterviewerPasswordSettingsGroup : IInterviewerPasswordSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class InterviewerPasswordSettings : IInterviewerPasswordSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public InterviewerPasswordSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// CATI interviewer expiration period in days.
        /// </summary>
        public int ExpirationPeriodInDays
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.ExpirationPeriodInDays);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.ExpirationPeriodInDays, value );
            }
        }
		
        /// <summary>
        /// CATI interviewer is required to change his password on the first login
        /// </summary>
        public bool IsChangeAfterFirstLoginRequired
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.IsChangeAfterFirstLoginRequired);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.IsChangeAfterFirstLoginRequired, value );
            }
        }
		
        /// <summary>
        /// Is complex password rule enforced for CATI interviewer password. Possible values: true or false. Complex password must must have at least 1 upper case character and 1 non-alphanumeric character.
        /// </summary>
        public bool IsComplexPasswordEnforced
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.IsComplexPasswordEnforced);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.IsComplexPasswordEnforced, value );
            }
        }
		
        /// <summary>
        /// Is CATI interviewer password expiration enabled. Possible values: true or false.
        /// </summary>
        public bool IsExpirationEnabled
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.IsExpirationEnabled);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.IsExpirationEnabled, value );
            }
        }
		
        /// <summary>
        /// Minimal allowed length of CATI interviewer password. If 0 then any length is allowed.
        /// </summary>
        public bool IsMinimumPasswordLengthEnforced
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.IsMinimumPasswordLengthEnforced);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.IsMinimumPasswordLengthEnforced, value );
            }
        }
		
        /// <summary>
        /// Can CATI interviewer set the same password during password change procedure. Possible values: true or false.
        /// </summary>
        public bool IsResetToSamePasswordEnabled
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.IsResetToSamePasswordEnabled);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.IsResetToSamePasswordEnabled, value );
            }
        }
		
        /// <summary>
        /// Minimal allowed length of CATI interviewer password. This option works only when IsMinimumPasswordLengthEnforced is True.
        /// </summary>
        public int MinimumPasswordLength
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerPassword.MinimumPasswordLength);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerPassword.MinimumPasswordLength, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
