//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IInterviewerPropertiesSettings
    {
		
        /// <summary>
        /// Enter up to five additional attribute names for an interviewer, separated by commas or semicolons. When you add attributes, the interviewer properties area will show one field for each attribute (up to five). If you leave this setting empty, no additional attributes section will appear.
        /// </summary>
        string AttributesList{ get; set; }
    }

	public interface IInterviewerPropertiesSettingsGroup : IInterviewerPropertiesSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class InterviewerPropertiesSettings : IInterviewerPropertiesSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public InterviewerPropertiesSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Enter up to five additional attribute names for an interviewer, separated by commas or semicolons. When you add attributes, the interviewer properties area will show one field for each attribute (up to five). If you leave this setting empty, no additional attributes section will appear.
        /// </summary>
        public string AttributesList
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.InterviewerProperties.AttributesList);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.InterviewerProperties.AttributesList, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
