//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IQuotasSettings
    {
		
        /// <summary>
        /// Maximum number of questions which CATI quota can be based on.
        /// </summary>
        int MaxQuestionsPerQuota{ get; set; }
    }

	public interface IQuotasSettingsGroup : IQuotasSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class QuotasSettings : IQuotasSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public QuotasSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Maximum number of questions which CATI quota can be based on.
        /// </summary>
        public int MaxQuestionsPerQuota
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Quotas.MaxQuestionsPerQuota);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Quotas.MaxQuestionsPerQuota, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
