//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IQuotaClusteringSettings
    {
		
        /// <summary>
        /// Quota clustering functionality is switched on/off.
        /// </summary>
        bool Enabled{ get; set; }
    }

	public interface IQuotaClusteringSettingsGroup : IQuotaClusteringSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class QuotaClusteringSettings : IQuotaClusteringSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public QuotaClusteringSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Quota clustering functionality is switched on/off.
        /// </summary>
        public bool Enabled
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.QuotaClustering.Enabled);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.QuotaClustering.Enabled, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
