//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IReplicationSettings
    {
		
        /// <summary>
        /// ReplicationThread interval (in ms).
        /// </summary>
        int BackgroundReplicationSleepPeriod{ get; set; }
		
        /// <summary>
        /// Timeout to get an exclusive lock (in ms).
        /// </summary>
        int ForceReplicationLockTimeout{ get; set; }
    }

	public interface IReplicationSettingsGroup : IReplicationSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class ReplicationSettings : IReplicationSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public ReplicationSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// ReplicationThread interval (in ms).
        /// </summary>
        public int BackgroundReplicationSleepPeriod
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Replication.BackgroundReplicationSleepPeriod);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Replication.BackgroundReplicationSleepPeriod, value );
            }
        }
		
        /// <summary>
        /// Timeout to get an exclusive lock (in ms).
        /// </summary>
        public int ForceReplicationLockTimeout
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Replication.ForceReplicationLockTimeout);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Replication.ForceReplicationLockTimeout, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
