//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IReviewerSettings
    {
		
        /// <summary>
        /// Maximum number of interviews for one session.
        /// </summary>
        string LimitOfAmountOfInterviewsPerSession{ get; set; }
		
        /// <summary>
        /// Url template for session to review.
        /// </summary>
        string SessionUrlTemplate{ get; set; }
    }

	public interface IReviewerSettingsGroup : IReviewerSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class ReviewerSettings : IReviewerSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public ReviewerSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Maximum number of interviews for one session.
        /// </summary>
        public string LimitOfAmountOfInterviewsPerSession
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Reviewer.LimitOfAmountOfInterviewsPerSession);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Reviewer.LimitOfAmountOfInterviewsPerSession, value );
            }
        }
		
        /// <summary>
        /// Url template for session to review.
        /// </summary>
        public string SessionUrlTemplate
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Reviewer.SessionUrlTemplate);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Reviewer.SessionUrlTemplate, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
