//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings.RoutineMaintenance.Actions
{
    public partial interface IMessageTableCleanupSettings
    {
		
        /// <summary>
        /// Time span from the current date after which records in the table will be deleted.
        /// </summary>
        TimeSpan ExpirationPeriod{ get; set; }
		
        /// <summary>
        /// Maintenance shift type which should be used for run this action.
        /// </summary>
        int ShiftType{ get; set; }
    }

	public interface IMessageTableCleanupSettingsGroup : IMessageTableCleanupSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class MessageTableCleanupSettings : IMessageTableCleanupSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public MessageTableCleanupSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Time span from the current date after which records in the table will be deleted.
        /// </summary>
        public TimeSpan ExpirationPeriod
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.MessageTableCleanup.ExpirationPeriod);
                return TimeSpan.Parse( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.MessageTableCleanup.ExpirationPeriod, value );
            }
        }
		
        /// <summary>
        /// Maintenance shift type which should be used for run this action.
        /// </summary>
        public int ShiftType
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.MessageTableCleanup.ShiftType);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.MessageTableCleanup.ShiftType, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
