//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;
using Confirmit.CATI.Core.SystemSettings.RoutineMaintenance;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IRoutineMaintenanceSettings
    {
		
		IActionsSettings Actions{ get; }
		
        /// <summary>
        /// The daily time at which the routine maintenance starts.
        /// </summary>
        TimeSpan DailyShiftStartTime{ get; set; }
		
        /// <summary>
        /// Routine maintenance duration.
        /// </summary>
        TimeSpan Duration{ get; set; }
		
        /// <summary>
        /// Frequency of execution routing maintance operation for each company from default backend instance.
        /// </summary>
        TimeSpan FrequencyExecution{ get; set; }
		
        /// <summary>
        /// Weeks offset from the start of the month when database cleanup starts. Cleanup time based on the DailyShiftStartTime.
        /// </summary>
        int MonthlyShiftWeekNumber{ get; set; }
		
        /// <summary>
        /// Days offset from the start of the week when database cleanup starts. Cleanup time based on the DailyShiftStartTime.
        /// </summary>
        int WeeklyShiftDayNumber{ get; set; }
    }

	public interface IRoutineMaintenanceSettingsGroup : IRoutineMaintenanceSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class RoutineMaintenanceSettings : IRoutineMaintenanceSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;
		
		private readonly IActionsSettingsGroup _Actions;

		public RoutineMaintenanceSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		
			_Actions = ServiceLocator.Resolve<IActionsSettingsGroup>();
		}
		
		public IActionsSettings Actions { get { return _Actions; } }
		
        /// <summary>
        /// The daily time at which the routine maintenance starts.
        /// </summary>
        public TimeSpan DailyShiftStartTime
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.DailyShiftStartTime);
                return TimeSpan.Parse( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.DailyShiftStartTime, value );
            }
        }
		
        /// <summary>
        /// Routine maintenance duration.
        /// </summary>
        public TimeSpan Duration
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Duration);
                return TimeSpan.Parse( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Duration, value );
            }
        }
		
        /// <summary>
        /// Frequency of execution routing maintance operation for each company from default backend instance.
        /// </summary>
        public TimeSpan FrequencyExecution
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.FrequencyExecution);
                return TimeSpan.Parse( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.FrequencyExecution, value );
            }
        }
		
        /// <summary>
        /// Weeks offset from the start of the month when database cleanup starts. Cleanup time based on the DailyShiftStartTime.
        /// </summary>
        public int MonthlyShiftWeekNumber
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.MonthlyShiftWeekNumber);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.MonthlyShiftWeekNumber, value );
            }
        }
		
        /// <summary>
        /// Days offset from the start of the week when database cleanup starts. Cleanup time based on the DailyShiftStartTime.
        /// </summary>
        public int WeeklyShiftDayNumber
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.WeeklyShiftDayNumber);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.WeeklyShiftDayNumber, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{
			_Actions.OnChanged();

			OnSettingsChanged();
		}
    }
}
