//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings.RoutineMaintenance.Actions
{
    public partial interface IDatabaseMaintenanceSettings
    {
		
        /// <summary>
        /// Rebuild index fragmentation threshold. If the index greater than the value of the threshold, we need to rebuild it.
        /// </summary>
        int FragmentationIndexRebuildThreshold{ get; set; }
		
        /// <summary>
        /// Reorganize index fragmentation threshold. If the index greater than the value of the threshold, we need to reorganize it.
        /// </summary>
        int FragmentationIndexReorganizeThreshold{ get; set; }
		
        /// <summary>
        /// List of ignored system indexes that will not be rebuilded/reorginized.
        /// </summary>
        string IgnoredIndexes{ get; set; }
		
        /// <summary>
        /// Is the name of the mode. mode specifies the scan level that is used to obtain statistics. mode is sysname. Valid inputs are DEFAULT, NULL, LIMITED, SAMPLED, or DETAILED. The default (NULL) is LIMITED.
        /// </summary>
        string IndexFragmentationDetectMode{ get; set; }
		
        /// <summary>
        /// If count of pages is used in index less than minimum index page count, so index willn't be rebuilded/reoginized.
        /// </summary>
        int MinIndexPageCount{ get; set; }
		
        /// <summary>
        /// Shift type of rebuild index activity.
        /// </summary>
        int RebuildIndexShiftType{ get; set; }
		
        /// <summary>
        /// Maintenance shift type which should be used for run this action.
        /// </summary>
        int ShiftType{ get; set; }
		
        /// <summary>
        /// A list of statistics(tables) that we need to update.
        /// </summary>
        string UpdateStatisticTables{ get; set; }
    }

	public interface IDatabaseMaintenanceSettingsGroup : IDatabaseMaintenanceSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class DatabaseMaintenanceSettings : IDatabaseMaintenanceSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public DatabaseMaintenanceSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Rebuild index fragmentation threshold. If the index greater than the value of the threshold, we need to rebuild it.
        /// </summary>
        public int FragmentationIndexRebuildThreshold
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.FragmentationIndexRebuildThreshold);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.FragmentationIndexRebuildThreshold, value );
            }
        }
		
        /// <summary>
        /// Reorganize index fragmentation threshold. If the index greater than the value of the threshold, we need to reorganize it.
        /// </summary>
        public int FragmentationIndexReorganizeThreshold
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.FragmentationIndexReorganizeThreshold);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.FragmentationIndexReorganizeThreshold, value );
            }
        }
		
        /// <summary>
        /// List of ignored system indexes that will not be rebuilded/reorginized.
        /// </summary>
        public string IgnoredIndexes
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.IgnoredIndexes);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.IgnoredIndexes, value );
            }
        }
		
        /// <summary>
        /// Is the name of the mode. mode specifies the scan level that is used to obtain statistics. mode is sysname. Valid inputs are DEFAULT, NULL, LIMITED, SAMPLED, or DETAILED. The default (NULL) is LIMITED.
        /// </summary>
        public string IndexFragmentationDetectMode
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.IndexFragmentationDetectMode);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.IndexFragmentationDetectMode, value );
            }
        }
		
        /// <summary>
        /// If count of pages is used in index less than minimum index page count, so index willn't be rebuilded/reoginized.
        /// </summary>
        public int MinIndexPageCount
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.MinIndexPageCount);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.MinIndexPageCount, value );
            }
        }
		
        /// <summary>
        /// Shift type of rebuild index activity.
        /// </summary>
        public int RebuildIndexShiftType
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.RebuildIndexShiftType);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.RebuildIndexShiftType, value );
            }
        }
		
        /// <summary>
        /// Maintenance shift type which should be used for run this action.
        /// </summary>
        public int ShiftType
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.ShiftType);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.ShiftType, value );
            }
        }
		
        /// <summary>
        /// A list of statistics(tables) that we need to update.
        /// </summary>
        public string UpdateStatisticTables
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.UpdateStatisticTables);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.RoutineMaintenance.Actions.DatabaseMaintenance.UpdateStatisticTables, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
