//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface ISchedulingScriptSettings
    {
		
        /// <summary>
        /// Enable restricted mode to check custom code.
        /// </summary>
        bool EnableRestrictedMode{ get; set; }
		
        /// <summary>
        /// Limit for amount of rows in BvScheduleError table
        /// </summary>
        int ErrorLogSize{ get; set; }
		
        /// <summary>
        /// Maximum amount of actions in scheduling script that can be executed without raising an error.
        /// </summary>
        int MaxActionsToExecute{ get; set; }
		
        /// <summary>
        /// Limit the amount of parameters in scheduling script.
        /// </summary>
        int MaxParameters{ get; set; }
		
        /// <summary>
        /// List of secure methods which can be called from scheduling script assembly.
        /// </summary>
        string SecureExternalMethods{ get; set; }
		
        /// <summary>
        /// Enable usage of direct database access for scheduling script F function instead of usage WebServ.
        /// </summary>
        bool UseDirectDbAccess{ get; set; }
    }

	public interface ISchedulingScriptSettingsGroup : ISchedulingScriptSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class SchedulingScriptSettings : ISchedulingScriptSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public SchedulingScriptSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Enable restricted mode to check custom code.
        /// </summary>
        public bool EnableRestrictedMode
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SchedulingScript.EnableRestrictedMode);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SchedulingScript.EnableRestrictedMode, value );
            }
        }
		
        /// <summary>
        /// Limit for amount of rows in BvScheduleError table
        /// </summary>
        public int ErrorLogSize
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SchedulingScript.ErrorLogSize);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SchedulingScript.ErrorLogSize, value );
            }
        }
		
        /// <summary>
        /// Maximum amount of actions in scheduling script that can be executed without raising an error.
        /// </summary>
        public int MaxActionsToExecute
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SchedulingScript.MaxActionsToExecute);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SchedulingScript.MaxActionsToExecute, value );
            }
        }
		
        /// <summary>
        /// Limit the amount of parameters in scheduling script.
        /// </summary>
        public int MaxParameters
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SchedulingScript.MaxParameters);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SchedulingScript.MaxParameters, value );
            }
        }
		
        /// <summary>
        /// List of secure methods which can be called from scheduling script assembly.
        /// </summary>
        public string SecureExternalMethods
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SchedulingScript.SecureExternalMethods);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SchedulingScript.SecureExternalMethods, value );
            }
        }
		
        /// <summary>
        /// Enable usage of direct database access for scheduling script F function instead of usage WebServ.
        /// </summary>
        public bool UseDirectDbAccess
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SchedulingScript.UseDirectDbAccess);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SchedulingScript.UseDirectDbAccess, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
