//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface IServerSettings
    {
		
        /// <summary>
        /// IP addresses which internal WCF services are allowed for.
        /// </summary>
        string AccessAllowedIPAddresses{ get; set; }
		
        /// <summary>
        /// Set minimum thread pool size during start of backend service if value is more then 0
        /// </summary>
        int BackendMinThreadPoolSize{ get; set; }
		
        /// <summary>
        ///  When enabled, new CATI databases for companies will be created from backup of main CATI database. Otherwise - using database deploy. Should be 'False' for Azure Managed SQL
        /// </summary>
        bool CreateCompanyDatabasesFromBackup{ get; set; }
		
        /// <summary>
        /// Start CATI instance service timeout (in sec).
        /// </summary>
        int ServiceStartTimeout{ get; set; }
    }

	public interface IServerSettingsGroup : IServerSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class ServerSettings : IServerSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public ServerSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// IP addresses which internal WCF services are allowed for.
        /// </summary>
        public string AccessAllowedIPAddresses
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Server.AccessAllowedIPAddresses);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Server.AccessAllowedIPAddresses, value );
            }
        }
		
        /// <summary>
        /// Set minimum thread pool size during start of backend service if value is more then 0
        /// </summary>
        public int BackendMinThreadPoolSize
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Server.BackendMinThreadPoolSize);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Server.BackendMinThreadPoolSize, value );
            }
        }
		
        /// <summary>
        ///  When enabled, new CATI databases for companies will be created from backup of main CATI database. Otherwise - using database deploy. Should be 'False' for Azure Managed SQL
        /// </summary>
        public bool CreateCompanyDatabasesFromBackup
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Server.CreateCompanyDatabasesFromBackup);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Server.CreateCompanyDatabasesFromBackup, value );
            }
        }
		
        /// <summary>
        /// Start CATI instance service timeout (in sec).
        /// </summary>
        public int ServiceStartTimeout
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Server.ServiceStartTimeout);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Server.ServiceStartTimeout, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
