//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface ISQLServerSettings
    {
		
        /// <summary>
        /// This timeout is used in Data Access Layer.
        /// </summary>
        int DefaultSqlCommandTimeout{ get; set; }
		
        /// <summary>
        /// This timeout is used in Data Access Layer.
        /// </summary>
        int DefaultSqlConnectionTimeout{ get; set; }
		
        /// <summary>
        /// Path to the master DB file (used in Backend instance registrator). Either both SqlServerDataPath and SqlServerLogPath should be empty or both should contain path.
        /// </summary>
        string SqlServerDataPath{ get; set; }
		
        /// <summary>
        /// Path to save DB logs. Either both SqlServerDataPath and SqlServerLogPath should be empty or both should contain path.
        /// </summary>
        string SqlServerLogPath{ get; set; }
    }

	public interface ISQLServerSettingsGroup : ISQLServerSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class SQLServerSettings : ISQLServerSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public SQLServerSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// This timeout is used in Data Access Layer.
        /// </summary>
        public int DefaultSqlCommandTimeout
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SQLServer.DefaultSqlCommandTimeout);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SQLServer.DefaultSqlCommandTimeout, value );
            }
        }
		
        /// <summary>
        /// This timeout is used in Data Access Layer.
        /// </summary>
        public int DefaultSqlConnectionTimeout
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SQLServer.DefaultSqlConnectionTimeout);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SQLServer.DefaultSqlConnectionTimeout, value );
            }
        }
		
        /// <summary>
        /// Path to the master DB file (used in Backend instance registrator). Either both SqlServerDataPath and SqlServerLogPath should be empty or both should contain path.
        /// </summary>
        public string SqlServerDataPath
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SQLServer.SqlServerDataPath);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SQLServer.SqlServerDataPath, value );
            }
        }
		
        /// <summary>
        /// Path to save DB logs. Either both SqlServerDataPath and SqlServerLogPath should be empty or both should contain path.
        /// </summary>
        public string SqlServerLogPath
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.SQLServer.SqlServerLogPath);
                return Convert.ToString( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.SQLServer.SqlServerLogPath, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
