//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;
using Confirmit.CATI.Core.SystemSettings.Supervisor;

namespace Confirmit.CATI.Core.SystemSettings
{
    public partial interface ISupervisorSettings
    {
		
		ISurveyListSettings SurveyList{ get; }
		
        /// <summary>
        /// When enabled - 1 sec refresh interval should become available in the refresh interval dropdown in Activity View - Interviewer List
        /// </summary>
        bool ActivityViewLoadTest{ get; set; }
		
        /// <summary>
        /// Number of rows on a single Interviewers List and Performance List page
        /// </summary>
        int ActivityViewPageSize{ get; set; }
		
        /// <summary>
        /// Indicates whether CATI Supervisor should always be loaded in a new style on launch.
        /// </summary>
        bool AlwaysOpenNewUI{ get; set; }
		
        /// <summary>
        /// Show classic style setting button in CATI Supervisor
        /// </summary>
        bool ShowClassicStyleButton{ get; set; }
		
        /// <summary>
        /// Indicates whether CATI Supervisor should show surveys list in old style.
        /// </summary>
        bool SurveysListOldStyleEnabled{ get; set; }
		
        /// <summary>
        /// When enabled, selection state on filtering and switching pages preserves. Works in the Interviewers List only
        /// </summary>
        bool TablesPreserveSelectionState{ get; set; }
    }

	public interface ISupervisorSettingsGroup : ISupervisorSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class SupervisorSettings : ISupervisorSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;
		
		private readonly ISurveyListSettingsGroup _SurveyList;

		public SupervisorSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		
			_SurveyList = ServiceLocator.Resolve<ISurveyListSettingsGroup>();
		}
		
		public ISurveyListSettings SurveyList { get { return _SurveyList; } }
		
        /// <summary>
        /// When enabled - 1 sec refresh interval should become available in the refresh interval dropdown in Activity View - Interviewer List
        /// </summary>
        public bool ActivityViewLoadTest
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Supervisor.ActivityViewLoadTest);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Supervisor.ActivityViewLoadTest, value );
            }
        }
		
        /// <summary>
        /// Number of rows on a single Interviewers List and Performance List page
        /// </summary>
        public int ActivityViewPageSize
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Supervisor.ActivityViewPageSize);
                return Convert.ToInt32( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Supervisor.ActivityViewPageSize, value );
            }
        }
		
        /// <summary>
        /// Indicates whether CATI Supervisor should always be loaded in a new style on launch.
        /// </summary>
        public bool AlwaysOpenNewUI
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Supervisor.AlwaysOpenNewUI);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Supervisor.AlwaysOpenNewUI, value );
            }
        }
		
        /// <summary>
        /// Show classic style setting button in CATI Supervisor
        /// </summary>
        public bool ShowClassicStyleButton
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Supervisor.ShowClassicStyleButton);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Supervisor.ShowClassicStyleButton, value );
            }
        }
		
        /// <summary>
        /// Indicates whether CATI Supervisor should show surveys list in old style.
        /// </summary>
        public bool SurveysListOldStyleEnabled
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Supervisor.SurveysListOldStyleEnabled);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Supervisor.SurveysListOldStyleEnabled, value );
            }
        }
		
        /// <summary>
        /// When enabled, selection state on filtering and switching pages preserves. Works in the Interviewers List only
        /// </summary>
        public bool TablesPreserveSelectionState
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Supervisor.TablesPreserveSelectionState);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Supervisor.TablesPreserveSelectionState, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{
			_SurveyList.OnChanged();

			OnSettingsChanged();
		}
    }
}
