//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a SettingGroup.tt T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     DO NOT EDIT THIS FILE MANUALLY
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Handmade.Cache;

namespace Confirmit.CATI.Core.SystemSettings.Toggle
{
    public partial interface ISupervisorSettings
    {
		
        /// <summary>
        /// Enable logging of uncaught JavaScript exceptions for CatiSupervisor
        /// </summary>
        bool EnableScriptErrorsLogging{ get; set; }
    }

	public interface ISupervisorSettingsGroup : ISupervisorSettings, ISystemSettingsNotifyChanged
	{
	}

    public partial class SupervisorSettings : ISupervisorSettingsGroup
    {
		private readonly ISystemSettingCache _systemSettingCache;

		public SupervisorSettings(ISystemSettingCache systemSettingCache)
		{
			_systemSettingCache = systemSettingCache;
		}
		
        /// <summary>
        /// Enable logging of uncaught JavaScript exceptions for CatiSupervisor
        /// </summary>
        public bool EnableScriptErrorsLogging
        { 
            get
            {
                var val = _systemSettingCache.Get(SystemSettingConstants.Toggle.Supervisor.EnableScriptErrorsLogging);
                return Convert.ToBoolean( val );
            }
            set
            {
                _systemSettingCache.Set(SystemSettingConstants.Toggle.Supervisor.EnableScriptErrorsLogging, value );
            }
        }

        partial void OnSettingsChanged();

		public void OnChanged()
		{

			OnSettingsChanged();
		}
    }
}
