{{- if and .Values.global.alerts.enabled .Values.alerts.enabled .Values.alerts.lokiRules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cati-supervisor-legacy-client.fullname" . }}-lokirules
  labels: {{ include "cati-supervisor-legacy-client.labels" . | nindent 4 }}
    loki_rule: ''
  annotations:
    k8s-sidecar-target-directory: /rules/fake
data:
  rules.yaml: |
    groups:
      - name: {{ include "cati-supervisor-legacy-client.fullname" . }}
        rules: {{ tpl .Values.alerts.lokiRules . | nindent 10 }}
{{- end }}
