{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cati-supervisor-legacy-client.serviceAccountName" . }}
  labels: {{- include "cati-supervisor-legacy-client.labels" . | nindent 4 }}
{{- end -}}
