//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BvSchScriptGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confirmit.CATI.Core.Schedules2007.BvSchScriptGen.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Actions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Action&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Suspend the interview&lt;/Name&gt;
        ///    &lt;HasParameter&gt;false&lt;/HasParameter&gt;
        ///    &lt;ParameterDescription /&gt;
        ///    &lt;ParameterTypeName /&gt;
        ///  &lt;/Action&gt;
        ///  &lt;Action&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///    &lt;Name&gt;Recall after number of minutes&lt;/Name&gt;
        ///    &lt;HasParameter&gt;true&lt;/HasParameter&gt;
        ///    &lt;ParameterDescription&gt;Number of minutes. Unsigned value, Min = 1, Q: Max = 1440 ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // JScript source code
        ///import System;
        ///import System.Collection;
        ///import System.Collection.Generic;
        ///import PtBvEventLibrary;
        ///import CustomCode;
        ///import JsDelegates;
        ///import PtBvQSLTranslatorLibrary;
        ///import Interpreter;
        ///
        ///package Interpreter
        ///{{
        ///    class Initializer
        ///    {{  
        ///       static private var schedule : Schedule = null;
        ///
        ///       //we needn&apos;t create instance this class
        ///       public function Initializer()
        ///       {{}}
        ///
        ///       //static constructor
        ///       static Initializer
        ///       {{
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Initializer {
            get {
                return ResourceManager.GetString("Initializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // JScript source code
        ///import PtBvQSLTranslatorLibrary;
        ///import PtBvCallQueueLibrary;
        ///import PtBvEventLibrary;
        ///import BVINTERVIEWLib;
        ///import BVDBSLib;
        ///import System;
        ///import Interpreter;
        ///import System.Text.RegularExpressions;
        ///import System.Collections.Generic;
        ///import System.Diagnostics;
        ///import BvDotNetScript;
        ///import System.Collections;
        ///
        ///package Interpreter
        ///{
        ///    class RulesInterpreter
        ///    {   
        ///       private var bvSchedule : IPtBvSchedule;
        ///       private var bvPoolSched : IPtBvPool;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interpreter {
            get {
                return ResourceManager.GetString("Interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DotNetScript&gt;
        ///	&lt;SourceFiles&gt;
        ///		&lt;SourceFile Name=&quot;initialize.js&quot; Language=&quot;JScript.Net&quot;&gt;
        ///			&lt;![CDATA[{0}]]&gt;
        ///		&lt;/SourceFile&gt;
        ///		&lt;SourceFile Name=&quot;wrapper.js&quot; Language=&quot;JScript.Net&quot;&gt;
        ///			&lt;![CDATA[{1}]]&gt;
        ///		&lt;/SourceFile&gt;
        ///		&lt;SourceFile Name=&quot;interpreter.js&quot; Language=&quot;JScript.Net&quot;&gt;
        ///			&lt;![CDATA[{4}]]&gt;
        ///		&lt;/SourceFile&gt;
        ///	&lt;/SourceFiles&gt;
        ///	&lt;References&gt;
        ///		&lt;Reference ref=&quot;{2}\Microsoft.NET\Framework\v2.0.50727\System.dll&quot; /&gt;
        ///		&lt;Reference ref=&quot;{3}BvEventu.Interop.dll&quot; /&gt;
        ///		&lt;Reference ref=&quot;{3}BVQSLTRANSLATORu.I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // JScript source code
        ///import System;
        ///import PtBvEventLibrary;
        ///import CustmoCode;
        ///import PtBvQSLTranslatorLibrary;
        ///
        ///package CustomCode
        ///{{   
        ///   {0} 
        ///}};.
        /// </summary>
        internal static string Wrapers {
            get {
                return ResourceManager.GetString("Wrapers", resourceCulture);
            }
        }
    }
}
