ALTER TABLE [dbo].[BvShift]
    ADD CONSTRAINT [BvPkShIFt] PRIMARY KEY CLUSTERED ([OwnerSID] ASC, [ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

