ALTER TABLE [dbo].[BvInterview]
    ADD CONSTRAINT [BvPk_int] PRIMARY KEY CLUSTERED ([SurveySID] ASC, [ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

