ALTER TABLE [dbo].[BvTimezoneShift]
    ADD CONSTRAINT [BvPkTimezoneShIFt] PRIMARY KEY CLUSTERED ([OwnerSID] ASC, [ShiftID] ASC, [TimezoneID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

