ALTER TABLE [dbo].[BvShiftType]
    ADD CONSTRAINT [IX_BvShiftType] UNIQUE NONCLUSTERED ([OwnerSID] ASC, [Name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

