ALTER TABLE [dbo].[BvShiftZones]
    ADD CONSTRAINT [IX_BvShiftZones] UNIQUE NONCLUSTERED ([TimeZoneID] ASC, [ShiftTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

