ALTER TABLE [dbo].[BvReport]
    ADD CONSTRAINT [PK__BvReport__267ABA7A] PRIMARY KEY CLUSTERED ([Rpt_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

