ALTER TABLE [dbo].[BvAppointment]
    ADD CONSTRAINT [Pk_app] PRIMARY KEY CLUSTERED ([ID] ASC, [SurveySID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

