ALTER TABLE [dbo].[BvPersonMonitoringLastID]
    ADD CONSTRAINT [PK_BvPersonMonitoringLastID] PRIMARY KEY NONCLUSTERED ([PersonSID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

