ALTER TABLE [dbo].[BvPersonMonitoringEvents]
    ADD CONSTRAINT [PK_BvPersonMonitoringEvents] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

