ALTER TABLE [dbo].[BvShiftType]
    ADD CONSTRAINT [PK_BvShiftType] PRIMARY KEY CLUSTERED ([ObjectID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

