ALTER TABLE [dbo].[BvState]
    ADD CONSTRAINT [PK_BvState] PRIMARY KEY CLUSTERED ([StateGroupID] ASC, [StateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

