ALTER TABLE [dbo].[BvScheduleParam]
    ADD CONSTRAINT [PK_BvScheduleParam_SurveySIDParamID] PRIMARY KEY CLUSTERED ([ScheduleID] ASC, [SurveySID] ASC, [ParamID] ASC ) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
