ALTER TABLE [dbo].[BvActiveShiftTypeZone]
    ADD CONSTRAINT [PK_BvActiveShiftTypeZone] PRIMARY KEY CLUSTERED ([Id] ASC, [SurveyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

