ALTER TABLE [dbo].[BvFilters]
    ADD CONSTRAINT [PK_BvFilters] PRIMARY KEY CLUSTERED ([SID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

