ALTER TABLE [dbo].[BvUserSurveyPermission]
    ADD CONSTRAINT [pk_BvUserSurveyPermission] PRIMARY KEY CLUSTERED ([UserName] ASC, [SurveySID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

