ALTER TABLE [dbo].[BvThresholdITS]
    ADD CONSTRAINT [Pk_BvThresholdITS] PRIMARY KEY CLUSTERED ([SurveySID] ASC, [ITS] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

