ALTER TABLE [dbo].[BvSchedule]
    ADD CONSTRAINT [PK_BvSchedule] PRIMARY KEY CLUSTERED ([ScheduleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

