ALTER TABLE [dbo].[BvSampleStatusSummary]
    ADD CONSTRAINT [Pk_BvSampleStatusSummary] PRIMARY KEY CLUSTERED ([SurveySID] ASC, [ITS] ASC, [IsCati] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

