ALTER TABLE [dbo].[BvAppointmentCounters]
    ADD CONSTRAINT [PkBvAppointmentCounters] PRIMARY KEY CLUSTERED ([SurveySID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

