ALTER TABLE [dbo].[BvAggregateSurvey]
    ADD CONSTRAINT [PkBvAggregateSurvey] PRIMARY KEY CLUSTERED ([SID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

