ALTER TABLE [dbo].[BvPersonGroup]
    ADD CONSTRAINT [PkBvPersonGroup] PRIMARY KEY CLUSTERED ([SID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

