//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapperLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BootstrapperLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bannrbmp {
            get {
                object obj = ResourceManager.GetObject("bannrbmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot encrypt section &apos;{0}&apos; in web.config.
        /// </summary>
        public static string CannotEncryptSectionInWebConfigFormat {
            get {
                return ResourceManager.GetString("CannotEncryptSectionInWebConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation does not have access to &apos;{0}&apos; server, because you have not permissions or the server is unavailable. Stop services manually and try again.
        /// </summary>
        public static string CurrentUserCannotAccesssToRemoteServer {
            get {
                return ResourceManager.GetString("CurrentUserCannotAccesssToRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site {0} has id={1}..
        /// </summary>
        public static string DifferentIdForWebSite {
            get {
                return ResourceManager.GetString("DifferentIdForWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a deploy login to continue.
        /// </summary>
        public static string EmptyDeployLogin {
            get {
                return ResourceManager.GetString("EmptyDeployLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a deploy password to continue.
        /// </summary>
        public static string EmptyDeployPassword {
            get {
                return ResourceManager.GetString("EmptyDeployPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during decryption of a password from the parameters file.
        ///Error message: {0}.
        /// </summary>
        public static string ErrorDuringDecriptAPasswordsFromFileWithParameters {
            get {
                return ResourceManager.GetString("ErrorDuringDecriptAPasswordsFromFileWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation has completed successfully.
        /// </summary>
        public static string InstallationHasFinishedSuccessfully {
            get {
                return ResourceManager.GetString("InstallationHasFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of certificates ({0}) with thumbprint &apos;{1}&apos; is wrong. There can be only one certificate with a tumbprint..
        /// </summary>
        public static string ManyCertificatesWithTheCurrentThumprint {
            get {
                return ResourceManager.GetString("ManyCertificatesWithTheCurrentThumprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with parameters &apos;{0}&apos; cannot be found.
        /// </summary>
        public static string NoFileWithParameters {
            get {
                return ResourceManager.GetString("NoFileWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file with the encryption key is not defined.
        ///.
        /// </summary>
        public static string NotDefinedPathToFileWithCryptographicKey {
            get {
                return ResourceManager.GetString("NotDefinedPathToFileWithCryptographicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the parameter file is not defined.
        ///.
        /// </summary>
        public static string NotDefinedPathToFileWithParameters {
            get {
                return ResourceManager.GetString("NotDefinedPathToFileWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encryption key file does not exist:
        ///{0}.
        /// </summary>
        public static string NotExistedCryptKeyFile {
            get {
                return ResourceManager.GetString("NotExistedCryptKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder in the PROCDUMP_LOG_FOLDER_PATH parameter does not exist..
        /// </summary>
        public static string NotExistedFolderInProcdumpLogFolderPathParameter {
            get {
                return ResourceManager.GetString("NotExistedFolderInProcdumpLogFolderPathParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site {0} cannot be found..
        /// </summary>
        public static string NotFoundWebSite {
            get {
                return ResourceManager.GetString("NotFoundWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation has found a file with installation parameters: {0}.
        ///Do you want to run a &quot;passive&quot; installation using parameters from this file?.
        /// </summary>
        public static string QuestionAboutUsingFileWithParameters {
            get {
                return ResourceManager.GetString("QuestionAboutUsingFileWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        public static string RemoveProduct {
            get {
                return ResourceManager.GetString("RemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action you want to perform.
        /// </summary>
        public static string SelectActionFormTitle {
            get {
                return ResourceManager.GetString("SelectActionFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use a silent mode because the product is not installed..
        /// </summary>
        public static string SilentModeForNotInstalledProduct {
            get {
                return ResourceManager.GetString("SilentModeForNotInstalledProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: setup.exe [/q] [/? | /update [/ignoreVersion] | /uninstall]
        /// /q             - Do not show any messages during installation. Default answers will be selected in question dialogs. Use this for automatic installations only.
        /// /?             - Show this help message
        /// /update        - Run installation as update (remove the previous version and install a new one). Get parameters from the registry.
        /// /ignoreVersion - Update version even if the existing version is bigger or the same as the current one.
        /// / [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StandardUsageInfo {
            get {
                return ResourceManager.GetString("StandardUsageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST_CERTIFICATE_NAME parameter must be filled because you specified &apos;Test&apos; value in the CERTIFICATE_TYPE property.
        /// </summary>
        public static string TestCertificateNameParameterMustBeFilled {
            get {
                return ResourceManager.GetString("TestCertificateNameParameterMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate will expire during {0} days.
        /// </summary>
        public static string TheCertificateWillExpireSoonFormat {
            get {
                return ResourceManager.GetString("TheCertificateWillExpireSoonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command line parameter: {0}
        ///{1}.
        /// </summary>
        public static string UnknownCommandLineParameter {
            get {
                return ResourceManager.GetString("UnknownCommandLineParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} (Unattended Mode).
        /// </summary>
        public static string UpdateProduct {
            get {
                return ResourceManager.GetString("UpdateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait. Installation in progress....
        /// </summary>
        public static string WaitInstallationInProgress {
            get {
                return ResourceManager.GetString("WaitInstallationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: the previous version of product is bigger than the current version.
        ///Check the box to install the current version whatever.
        /// </summary>
        public static string WarningPreviousVersionIsBiggerThanTheCurentOne {
            get {
                return ResourceManager.GetString("WarningPreviousVersionIsBiggerThanTheCurentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The product version you are installing is the same as the version already installed. Check the box to continue the installation anyway.
        /// </summary>
        public static string WarningVersionsAreTheSame {
            get {
                return ResourceManager.GetString("WarningVersionsAreTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update parameter count is wrong.
        ///.
        /// </summary>
        public static string WrongCountOfUpdateParameters {
            get {
                return ResourceManager.GetString("WrongCountOfUpdateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;INSTALL_LOCATION&apos; is wrong. You do not have creation rights in this folder..
        /// </summary>
        public static string WrongInstallLocationParameterNoCreationRights {
            get {
                return ResourceManager.GetString("WrongInstallLocationParameterNoCreationRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;INSTALL_LOCATION&apos; is wrong. The system has not &apos;{0}&apos; drive.
        /// </summary>
        public static string WrongInstallLocationParameterNoDrive {
            get {
                return ResourceManager.GetString("WrongInstallLocationParameterNoDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;INSTALL_LOCATION&apos; is wrong. You do not have deletion rights in this folder..
        /// </summary>
        public static string WrongInstallLocationParameterNoRemovingRights {
            get {
                return ResourceManager.GetString("WrongInstallLocationParameterNoRemovingRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;INSTALL_LOCATION&apos; is wrong. It is too short..
        /// </summary>
        public static string WrongInstallLocationParameterTooShort {
            get {
                return ResourceManager.GetString("WrongInstallLocationParameterTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has wrong value &apos;{1}&apos;
        ///Acceptable values are &apos;{2}&apos;.
        ///.
        /// </summary>
        public static string WrongParameterValueAndAcceptableValue {
            get {
                return ResourceManager.GetString("WrongParameterValueAndAcceptableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installation package is not supported by this processor type. Contact your product vendor..
        /// </summary>
        public static string WrongSystemType {
            get {
                return ResourceManager.GetString("WrongSystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use both the &apos;update&apos; and the &apos;uninstall&apos; parameters..
        /// </summary>
        public static string YouCannotUseBothUpdateAndUninstallParameters {
            get {
                return ResourceManager.GetString("YouCannotUseBothUpdateAndUninstallParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a path to the ProcDump.exe file in PROCDUMP_FILE_PATH parameter..
        /// </summary>
        public static string YouMustSpecifyAPathToProcDumpExeFile {
            get {
                return ResourceManager.GetString("YouMustSpecifyAPathToProcDumpExeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify both parameters: PROCDUMP_FILE_PATH and PROCDUMP_LOG_FOLDER_PATH..
        /// </summary>
        public static string YouShouldSpecifyBothProcdumpParameters {
            get {
                return ResourceManager.GetString("YouShouldSpecifyBothProcdumpParameters", resourceCulture);
            }
        }
    }
}
