CREATE CLUSTERED INDEX [IX_History_Main] ON [dbo].[BvHistory] 
(
	[SurveyId] ASC,
	[RoleID] ASC,
	[FiredTime] ASC,
	[ITS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

