CREATE UNIQUE NONCLUSTERED INDEX [IX_BvTelephoneBlacklist] ON [dbo].[BvTelephoneBlacklist]
(
	[Type] ASC,
	[TelephoneNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
