CREATE UNIQUE CLUSTERED INDEX [IX_BvLoginGroup]
    ON [dbo].[BvLoginGroup]([PersonSID] ASC, [ObjectSID] ASC, SurveySid) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = ON, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

