CREATE NONCLUSTERED INDEX [IX_BvPersonDeferredMonitoring] ON [dbo].[BvPersonDeferredMonitoring] 
(
	[PersonSID] ASC,
	[IsRecording] ASC,
	[IsComplete] ASC
)
INCLUDE ( [ID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
