//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Supervisor.Persons
{


    public partial class ChangeSSOIntegration
    {

        /// <summary>
        /// dialog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.Dialog dialog;

        /// <summary>
        /// lblSSOIntegration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSSOIntegration;

        /// <summary>
        /// ddlSSOIntegration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlSSOIntegration;

        /// <summary>
        /// ChangeSSO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer ChangeSSO;
    }
}
