namespace BvDotNetScript.ScriptObjects
{
    public enum ExtendedStatus
    {
        NotDefined = -1,
        Appointment = 1,
        Busy = 2,
        NoReply = 3,
        QuotaFail = 4,
        Refusal = 5,
        Terminated = 6,
        AnswerMachine = 7,
        Modem = 8,
        Fax = 9,
        Congestion = 10,
        Unobtainable = 11,
        Nuisance = 12,
        Completed = 13,
        Screened = 14,
        ReturnedNotDialled = 15,
        FreshSample = 16,
        Blacklist = 17,
        NotAutomaticallyDialled = 18,
        TransferToWeb = 20,
        TransferToCati = 21,
        TransferToCapi = 22,
        TransferToIvr = 23,
        InterruptedByInterviewer = 24,
        ReturnedDiallerExpired = 25,
        InterruptedBySystem = 26,
        FilteredByCallDelivery = 27,
        Stopped = 28,
        TelephonyFailure = 29,
        Error = 30,
        InboundCall = 1000,
        InboundCallDroppedByRespondent = 1001,
        InternalTransfer = 1010,
        ExternalTransfer = 1011,
        CanceledTransfer = 1012,
        DialingInterrupted = 1020,
        ExternallyValidatedNumber = 1021,
        SurveyScriptError = 1051,
        SynchronizedSample = 1052
    }
}