using System.ComponentModel;

namespace Confirmit.CATI.Core.Services.CheckSpelling
{
    public enum SupportedLanguage
    {
        [Description("bg-BG")]
        Bulgarian,
        [Description("he-IL")]
        Hebrew,
        [Description("ca-ES")]
        Catalan,
        [Description("cs-CZ")]
        Czech,
        [Description("da-DK")]
        Danish,
        [Description("de-DE")]
        German,
        [Description("de-CH")]
        GermanSwitzerland,
        [Description("es-ES")]
        Spanish,
        [Description("es-MX")]
        SpanishMexico,
        [Description("fr-FR")]
        French,
        [Description("hr-HR")]
        Croatian,
        [Description("it-IT")]
        Italian,
        [Description("pl-PL")]
        Polish,
        [Description("pt-PT")]
        Portuguese,
        [Description("pt-BR")]
        PortugueseBrazil,
        [Description("ro-RO")]
        Romanian,
        [Description("ru-RU")]
        Russian,
        [Description("sv-SE")]
        Swedish,
        [Description("uk-UA")]
        Ukrainian,
        [Description("sl-SI")]
        Slovenian,
        [Description("li-LI")]
        Lithuanian,
        [Description("af-ZA")]
        AfricanSouthAfrica,
        [Description("id-ID")]
        Indonesian,
        [Description("nl-NL")]
        DutchNetherlands,
        [Description("nb-NO")]
        NorwegianBokmal,
        [Description("nn-NO")]
        NorwegianNyNorsk,
        [Description("ms-MY")]
        Malay,
        [Description("en-GB")]
        EnglishUK,
        [Description("en-AU")]
        EngslishAustralia,
        [Description("en-CA")]
        EnglishCanadian,
        [Description("en-NZ")]
        EnglishNewZeeland,
        [Description("en-Us")]
        English
    }
}
