//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Core.Schedules2007.BvSchScriptGen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confirmit.CATI.Core.Schedules2007.BvSchScriptGen.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action type is not initialized..
        /// </summary>
        internal static string ActionNotInitializedMessage {
            get {
                return ResourceManager.GetString("ActionNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in action: &apos;{0}&apos;. The specified group either does not exist or is an administrative group..
        /// </summary>
        internal static string ActionParameterInvalidGroupMessage {
            get {
                return ResourceManager.GetString("ActionParameterInvalidGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in action: &apos;{0}&apos;. The action parameter has invalid type..
        /// </summary>
        internal static string ActionParameterInvalidType {
            get {
                return ResourceManager.GetString("ActionParameterInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in action: &apos;{0}&apos;. Action parameter is not specified..
        /// </summary>
        internal static string ActionParameterNotSpecifiedMessage {
            get {
                return ResourceManager.GetString("ActionParameterNotSpecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in action: &apos;{0}&apos;. Action parameter type is not specified or is wrong..
        /// </summary>
        internal static string ActionParameterTypeNotSpecifiedMessage {
            get {
                return ResourceManager.GetString("ActionParameterTypeNotSpecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in action: &apos;{0}&apos;. Specified user or group doesn&apos;t exist..
        /// </summary>
        internal static string ActionParameterUserOrGroupDoesntExistMessage {
            get {
                return ResourceManager.GetString("ActionParameterUserOrGroupDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in action: &apos;{0}&apos;. The action parameter value is invalid..
        /// </summary>
        internal static string ActionParameterValueInvalid {
            get {
                return ResourceManager.GetString("ActionParameterValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get timeZone with ID {0}.
        /// </summary>
        internal static string CantGetTimeZoneMessage {
            get {
                return ResourceManager.GetString("CantGetTimeZoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item should have specified color..
        /// </summary>
        internal static string ColorNotInitializedMessage {
            get {
                return ResourceManager.GetString("ColorNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date in not initialized..
        /// </summary>
        internal static string EndDateNotInitializedMessage {
            get {
                return ResourceManager.GetString("EndDateNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current exclusion intersects with exclusion with identifier {0} in timezone {1}..
        /// </summary>
        internal static string ExclusionIntersectionMessage {
            get {
                return ResourceManager.GetString("ExclusionIntersectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only exclusion shift type is allowed for exclusion object..
        /// </summary>
        internal static string ExclusionTypeExceptionMessage {
            get {
                return ResourceManager.GetString("ExclusionTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item identifier is not initialized..
        /// </summary>
        internal static string IdentifierNotInitializedMessage {
            get {
                return ResourceManager.GetString("IdentifierNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is less than zero or is greater than collection size..
        /// </summary>
        internal static string IndexOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t convert string &apos;{0}&apos; to GUID value..
        /// </summary>
        internal static string InvalidGuidStringMessage {
            get {
                return ResourceManager.GetString("InvalidGuidStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is in invalid state..
        /// </summary>
        internal static string InvalidItemExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidItemExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with identifier {0} was not found in the collection..
        /// </summary>
        internal static string ItemNotFoundMessage {
            get {
                return ResourceManager.GetString("ItemNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not initialized..
        /// </summary>
        internal static string ItemNotInitializedExceptionMessage {
            get {
                return ResourceManager.GetString("ItemNotInitializedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cannot be null..
        /// </summary>
        internal static string ItemNullExceptionMessage {
            get {
                return ResourceManager.GetString("ItemNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item should have name..
        /// </summary>
        internal static string NameNotInitializedMessage {
            get {
                return ResourceManager.GetString("NameNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value &apos;{0}&apos; couldn&apos;t be converted to action parameter type..
        /// </summary>
        internal static string ParameterValueCouldntBeConvertedMessage {
            get {
                return ResourceManager.GetString("ParameterValueCouldntBeConvertedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove null value..
        /// </summary>
        internal static string RemovedItemCannotBeNullException {
            get {
                return ResourceManager.GetString("RemovedItemCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respondent.
        /// </summary>
        internal static string RespondentTimezoneName {
            get {
                return ResourceManager.GetString("RespondentTimezoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule {0} is used in &apos;Set next rule&apos; action of sub-rule {1}.{2}..
        /// </summary>
        internal static string RuleIsInUseMessage {
            get {
                return ResourceManager.GetString("RuleIsInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule or sub-rule number should be in format &quot;number&quot; or &quot;number.number&quot;..
        /// </summary>
        internal static string RuleNumberFormatExceptionMessage {
            get {
                return ResourceManager.GetString("RuleNumberFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current shift intersects with shift with identifier {0} in timezone {1}..
        /// </summary>
        internal static string ShiftIntersectionMessage {
            get {
                return ResourceManager.GetString("ShiftIntersectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift type &apos;{0}&apos; is used in {1} with identifier {2}..
        /// </summary>
        internal static string ShiftTypeIsInUseMessage {
            get {
                return ResourceManager.GetString("ShiftTypeIsInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift type is not initialized..
        /// </summary>
        internal static string ShiftTypeNotInitializedMessage {
            get {
                return ResourceManager.GetString("ShiftTypeNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is greater than end date..
        /// </summary>
        internal static string StartDateGreaterEndDateMessage {
            get {
                return ResourceManager.GetString("StartDateGreaterEndDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date in not initialized..
        /// </summary>
        internal static string StartDateNotInitializedMessage {
            get {
                return ResourceManager.GetString("StartDateNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-rule {0} is used in &apos;Go to&apos; action of sub-rule {1}..
        /// </summary>
        internal static string SubRuleIsInUseMessage {
            get {
                return ResourceManager.GetString("SubRuleIsInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timezone does not exist in the list of timezones and is not Respondent timezone..
        /// </summary>
        internal static string TimezoneOutOfRangeException {
            get {
                return ResourceManager.GetString("TimezoneOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action with identifier &apos;{0}&apos; doesn&apos;t belong to actions dictionary..
        /// </summary>
        internal static string UnrecognizedActionMessage {
            get {
                return ResourceManager.GetString("UnrecognizedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no event handler attached to validation event..
        /// </summary>
        internal static string ValidationNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationNotSupportedExceptionMessage", resourceCulture);
            }
        }
    }
}
