//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Backend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SupervisorMultimodeInstance")]
        public string SupervisorServiceBaseAddress {
            get {
                return ((string)(this["SupervisorServiceBaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ManagementMultimodeInstance")]
        public string ManagementServiceBaseAddress {
            get {
                return ((string)(this["ManagementServiceBaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ManagementMultimodeInstance")]
        public string InstanceManagementServiceBaseAddress {
            get {
                return ((string)(this["InstanceManagementServiceBaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost/DialerMultimodeInstance")]
        public string DialerEventsHandlerServiceBaseAddress {
            get {
                return ((string)(this["DialerEventsHandlerServiceBaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost/ErrorReportingMultimodeInstance")]
        public string ErrorReportingServiceBaseAddress {
            get {
                return ((string)(this["ErrorReportingServiceBaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AreMetricsEnabled {
            get {
                return ((bool)(this["AreMetricsEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://*:9866")]
        public string MetricsUrl {
            get {
                return ((string)(this["MetricsUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cati-backend-master/ErrorReportingMultimodeInstanceHttp")]
        public string ErrorReportingInternalServiceBaseAddress {
            get {
                return ((string)(this["ErrorReportingInternalServiceBaseAddress"]));
            }
            set {
                this["ErrorReportingInternalServiceBaseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cati-backend-{companyId}/DialerMultimodeInstanceHttp")]
        public string DialerEventsHandlerInternalServiceBaseAddress {
            get {
                return ((string)(this["DialerEventsHandlerInternalServiceBaseAddress"]));
            }
            set {
                this["DialerEventsHandlerInternalServiceBaseAddress"] = value;
            }
        }
    }
}
