apiVersion: v1
kind: Service
metadata:
  name: {{ template "aws-connect-dialer-proxy.fullname" . }}
  labels: {{ include "aws-connect-dialer-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-app
      protocol: TCP
      name: http
  selector: {{- include "aws-connect-dialer-proxy.serviceSelectorLabels" . | nindent 4 }}
