{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-connect-dialer-proxy.serviceAccountName" . }}
  labels: {{- include "aws-connect-dialer-proxy.labels" . | nindent 4 }}
{{- end -}}
