{{- if and .Values.global.httpRouteMesh.enabled .Values.httpRouteMesh.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "cati-dialer-simulator.fullname" . }}-mesh
  labels: {{ include "cati-dialer-simulator.labels" . | nindent 4 }}
    app.confirmit.com/traffic-type: mesh
spec:
  parentRefs:
  - kind: Service
    name: '{{ template "cati-dialer-simulator.fullname" . }}'
    port: {{ .Values.service.port }}
  rules: {{ tpl (.Values.httpRouteMesh.rules | toYaml) . | nindent 2 }}
{{- end }}