{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cati-dialer-simulator.serviceAccountName" . }}
  labels: {{- include "cati-dialer-simulator.labels" . | nindent 4 }}
{{- end -}}
