CREATE TABLE [dbo].[BvAggregateSurveyAlertStatus] (
    [SID]                                      INT            NOT NULL,
    [Name]                                     NVARCHAR (255) NOT NULL,
    [Description]                              NVARCHAR (255) NOT NULL,
    [InterviewersLoggedCount]                  INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_InterviewersLoggedCount DEFAULT (0),
    [InterviewersLoggedCountPrev]              INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_InterviewersLoggedCountPrev DEFAULT (0),
    [NextAppointmentTime]                      DATETIME       NULL,
    [TotalSampleSize]                          INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_TotalSampleSize DEFAULT (0),
    [ScheduledCallsCount]                      INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_ScheduledCallsCount DEFAULT (0),
    [ScheduledCallsCountPrev]                  INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_ScheduledCallsCountPrev DEFAULT (0),
    [SuspendedCallsCount]                      INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_SuspendedCallsCount DEFAULT (0),
    [SuspendedCallsCountPrev]                  INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_SuspendedCallsCountPrev DEFAULT (0),
    [MinutesSpentWorkingOnSurvey]              INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_MinutesSpentWorkingOnSurvey DEFAULT (0),
    [AssignedInterviewersCount]                INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AssignedInterviewersCount DEFAULT (0),
    [StrikeRate]                               INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_StrikeRate DEFAULT (0),
    [CountCalls]                               INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_CountCalls DEFAULT (0),
    [AvgDuration]                              INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AvgDuration DEFAULT (0),
    [AlertStatusOfInterviewersLoggedCount]     INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfInterviewersLoggedCount DEFAULT (0),
    [AlertStatusOfNextAppointmentTime]         INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfNextAppointmentTime DEFAULT (0),
    [AlertStatusOfTotalSampleSize]             INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfTotalSampleSize DEFAULT (0),
    [AlertStatusOfScheduledCallsCount]         INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfScheduledCallsCount DEFAULT (0),
    [AlertStatusOfSuspendedCallsCount]         INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfSuspendedCallsCount DEFAULT (0),
    [AlertStatusOfMinutesSpentWorkingOnSurvey] INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfMinutesSpentWorkingOnSurvey DEFAULT (0),
    [AlertStatusOfAssignedInterviewersCount]   INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfAssignedInterviewersCount DEFAULT (0),
    [AlertStatusOfStrikeRate]                  INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfStrikeRate DEFAULT (0),
    [AlertStatusOfCountCalls]                  INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfCountCalls DEFAULT (0),
    [MaxStatusOfITSAlerts]                     INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_MaxStatusOfITSAlerts DEFAULT (0),
    [StrikeRate1h]                             INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_StrikeRate1h DEFAULT (0),
    [CountCalls1h]                             INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_CountCalls1h DEFAULT (0),
    [AvgDuration1h]                            INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AvgDuration1h DEFAULT (0),
	[MinutesSpentWorkingOnSurveyInDay]         INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_MinutesSpentWorkingOnSurveyInDay DEFAULT (0),
    [AlertStatusOfStrikeRate1h]                INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfStrikeRate1h DEFAULT (0),
    [AlertStatusOfCountCalls1h]                INT            NOT NULL CONSTRAINT DF_BvAggregateSurveyAlertStatus_AlertStatusOfCountCalls1h DEFAULT (0)
);

