CREATE TABLE BvCallCenter
(
	ID INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(MAX) NOT NULL,
	Description NVARCHAR(MAX),
	IsDefault BIT NOT NULL CONSTRAINT DF_IsDefault DEFAULT(0),
	CanBeDeleted BIT NOT NULL CONSTRAINT DF_CanBeDeleted DEFAULT(0),
	LocalTimezoneId INT NOT NULL,
	[DialerId] INT NOT NULL CONSTRAINT DF_BvCallCenter_DialerId DEFAULT (0), 
	HidePii BIT NOT NULL CONSTRAINT DF_HidePii DEFAULT(0),
    CONSTRAINT PK_BvCallCenter PRIMARY KEY ( ID )
)
