CREATE TABLE [dbo].[BvHistory] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [SurveyId]       INT            NOT NULL,
    [TelephoneNumber]NVARCHAR (255) NULL,
    [FiredTime]      DATETIME       NOT NULL,
    [InterviewId]    INT            NULL,
    [ITS]            SMALLINT		NULL,
    [AppointmentID]  INT            NULL,
    [WaitingTime]    INT            NULL,
    [ConfirmitDuration] INT         NULL,
    [Duration]       INT            NULL,
    [BatchId]        INT            NULL,
    [PersonSID]      INT            NULL,
    [RoleID]         TINYINT        NULL,
	[CallCenterID]	 INT			NOT NULL, 
    [OpenEndReviewDuration] INT    NULL, 
    [LinkedInterviewSessionId] INT NULL, 
    [DisplayTime] INT NULL, 
    [PreviewTime] INT NULL, 
    [ConnectedTime] INT NULL, 
    [WrapTime] INT NULL,
    [DialTypeId] TINYINT NULL,
    [CallAttemptNumber] INT NULL,
    [SessionId] INT NULL,
    [Custom1] NVARCHAR(50) NULL,
    [Custom2] NVARCHAR(50) NULL,
    [Custom3] NVARCHAR(50) NULL,
    [Custom4] NVARCHAR(50) NULL,
    [Custom5] NVARCHAR(50) NULL,
    CONSTRAINT PK_BvHistory_Id PRIMARY KEY NONCLUSTERED ([Id])
);

