CREATE TABLE [dbo].[BvSurvey] (
    [SID]                  INT             NOT NULL,
    [Number]               INT             NOT NULL,
    [Name]                 NVARCHAR (255)  NULL,
    [Description]          NVARCHAR (255)  NULL,
    [QuotaType]            TINYINT         NOT NULL,
    [State]                INT             NOT NULL,
    [ForceOpnRev]          INT             NOT NULL CONSTRAINT DF_BvSurvey_ForceOpnRev DEFAULT (0),
    [StateGroupID]         INT             NOT NULL CONSTRAINT DF_BvSurvey_StateGroupID DEFAULT (0),
    [RecWholeInt]          INT             NOT NULL CONSTRAINT DF_BvSurvey_RecWholeInt DEFAULT (0),
	[InterviewScreenRecording]	bit		   NOT NULL CONSTRAINT DF_BvSurvey_InterviewScreenRecording DEFAULT (0),
    [CfDbSchemaPath]       NVARCHAR (255)  NOT NULL CONSTRAINT DF_BvSurvey_CfDbSchemaPath DEFAULT (N''),
    [DestinationTableName] NVARCHAR (255)  NULL, 
    [ReplicationStatus]	   BIT			   NULL,
    [ScheduleID]           INT             NOT NULL,
    [DialerParameters]     NVARCHAR(MAX),
	[DialMode]             TINYINT         NOT NULL,
    [IsTelephoneBlacklistSupported] BIT NOT NULL CONSTRAINT DF_BvSurvey_IsTelephoneBlacklistSupported DEFAULT (0),
    [NotificationEmail]	   NVARCHAR(MAX) NULL, -- Email address to receive emails triggered by scripting errors in an interview.
    [IsRandomCallDeliveryEnabled] BIT NOT NULL CONSTRAINT DF_BvSurvey_IsRandomCallDeliveryEnabled DEFAULT (0),
    [EnforceHttps]         BIT NOT NULL CONSTRAINT DF_BvSurvey_EnforceHttps DEFAULT(0),
    [LastTouchTime]        SMALLDATETIME CONSTRAINT DF_BvSurvey_LastTouchTime DEFAULT(GETUTCDATE()),
	[SurveySchedulingMode]     SMALLINT NOT NULL CONSTRAINT DF_BvSurvey_SurveySchedulingMode DEFAULT(0),
	[SurveySqlServerName]  NVARCHAR(255)    NULL,
	[ClusteredQuotaName]  NVARCHAR(256) NULL,
	[ClusteredQuotaThreshold]  INT NOT NULL CONSTRAINT DF_BvSurvey_ClusteredQuotaThreshold DEFAULT(0),
    [DialerId] INT NULL, 
    [Target] INT NULL,
	[IsRespondentsDynamicCreationAllowed] BIT NOT NULL CONSTRAINT DF_BvSurvey_IsRespondentsDynamicCreationAllowed DEFAULT (0),
	[InternalTransferType] TINYINT NOT NULL CONSTRAINT DF_BvSurvey_InternalTransferType DEFAULT (1),
	[ExternalTransferType] TINYINT NOT NULL CONSTRAINT DF_BvSurvey_ExternalTransferType DEFAULT (1),
	[IsLiveMonitoringEnabled] BIT NOT NULL CONSTRAINT DF_BvSurvey_IsLiveMonitoringEnabled DEFAULT (1),
	[IsQuotaInCatiDb]	   BIT	   NULL,
	[InboundCallBehavior] TINYINT NOT NULL CONSTRAINT DF_BvSurvey_InboundCallBehavior DEFAULT (0),
    [DisableClrForFcd] BIT NOT NULL CONSTRAINT DF_BvSurvey_DisableClrForFcd DEFAULT (0), 
    [Comment] NVARCHAR(100) NULL,
    [IsStateLocked] BIT NOT NULL CONSTRAINT DF_BvSurvey_IsStateLocked DEFAULT (0)
);

