CREATE TABLE [dbo].[BvTasks] (
    [SurveySID]               INT               NOT NULL,
    [InterviewID]             INT               NOT NULL,
    [PersonSID]               INT               NOT NULL,
    [TimeCallDelivered]       DATETIME          NULL,
    [State]                   NVARCHAR (256)    NULL,
    [TimeStateChanged]        DATETIME          NULL,
    [TzID]                    INT               NOT NULL CONSTRAINT DF_BvTasks_TzID DEFAULT (0),
    [DiallingMode]            INT               NOT NULL CONSTRAINT DF_BvTasks_DiallingMode DEFAULT (0),
    [CallOutcome]             INT               NOT NULL CONSTRAINT DF_BvTasks_CallOutcome DEFAULT (-1),
    [InterviewState]          TINYINT           NOT NULL CONSTRAINT DF_BvTasks_InterviewState DEFAULT (0),
    [StatusLogout]            TINYINT           NOT NULL CONSTRAINT DF_BvTasks_StatusLogout DEFAULT (0),
    [LoggedInToDialerState]   TINYINT           NOT NULL CONSTRAINT DF_BvTasks_LoggedInToDialerState DEFAULT (0),
    [IsLoginRCToDialer]       BIT               NOT NULL CONSTRAINT DF_BvTasks_IsLoginRCToDialer DEFAULT (0),
    [CallID]                  INT               NULL,
    [LastKeepAliveTime]       DATETIME          NULL,
    [ProblemId]               INT               NOT NULL CONSTRAINT DF_BvTasks_ProblemId DEFAULT (0),
    [LockTime]                SMALLDATETIME     NULL,
    [StationId]               NVARCHAR(256)     NOT NULL CONSTRAINT DF_BvTasks_StationId DEFAULT (''),
    [StartTime]               DATETIME          NULL,
    [AuthenticationKey]       uniqueidentifier  NULL,
    [StartSessionTime]        DATETIME          NOT NULL,
    [EncryptionKey]           VARBINARY(64)     NOT NULL,
    [EncryptionIV]            VARBINARY(64)     NOT NULL,
    [DialerId]                INT               NOT NULL CONSTRAINT DF_BvTasks_DialerId DEFAULT (0),
    [StationExtensionNumber]  NVARCHAR(256)     NOT NULL CONSTRAINT DF_BvTasks_StationExtensionNumber DEFAULT (''),
    [IsDialerAgentLocal]      BIT               NOT NULL CONSTRAINT DF_BvTasks_IsDialerAgentLocal DEFAULT (0),
    [CallCenterID]            INT               NOT NULL,
    [SessionId]               INT               NOT NULL,
    [NewSurveySID]            INT               NOT NULL CONSTRAINT DF_BvTasks_NewSurveySID DEFAULT (0),
	[DialTypeId]              TINYINT           NOT NULL, 
    [OpenEndReviewStartTime]  DATETIME			NULL,
	[CurrentUtcTime]		  AS dbo.GetUtcNow(),
	[CallType]                TINYINT           NOT NULL CONSTRAINT DF_BvTasks_CallType DEFAULT (0), 
    [LinkedCallId] INT NULL, 
    [LinkedChain] NVARCHAR(MAX) NULL, 
    [LinkedInterviewSessionId] INT NULL,
	[SelectedSurveyId] INT NULL,
	[JsonContext] NVARCHAR(MAX) NULL,
	[CallConnectionState] TINYINT  NOT NULL CONSTRAINT DF_BvTasks_CallConnectionState DEFAULT (0),
	[BreakTypeId] INT NULL,
	[IsWebConsole] BIT NOT NULL  CONSTRAINT DF_BvTasks_IsWebConsole DEFAULT (0),
	[JsonWebConsoleState] NVARCHAR(MAX) NULL
);
