//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Supervisor.Resources
{


    public partial class DdiNumbersRecordedMessages
    {

        /// <summary>
        /// Toolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.GeneralToolbar Toolbar;

        /// <summary>
        /// ButtonSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.XpMenuItem ButtonSave;

        /// <summary>
        /// ParametersHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.Hint ParametersHint;

        /// <summary>
        /// stateChecker control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.StateChecker stateChecker;

        /// <summary>
        /// DefaultRepeatColumnTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatColumnTitle;

        /// <summary>
        /// ddlIncomingCallCompulsoryMessageUrlRepeatCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlIncomingCallCompulsoryMessageUrlRepeatCount;

        /// <summary>
        /// LabelIncomingCallCompulsoryMessageErrorAsterisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelIncomingCallCompulsoryMessageErrorAsterisk;

        /// <summary>
        /// TextBoxIncomingCallCompulsoryMessageUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxIncomingCallCompulsoryMessageUrl;

        /// <summary>
        /// DefaultRepeatIncomingCallCompulsoryMessageUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatIncomingCallCompulsoryMessageUrl;

        /// <summary>
        /// TextBoxDefaultRepeatIncomingCallCompulsoryMessageUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TextBoxDefaultRepeatIncomingCallCompulsoryMessageUrl;

        /// <summary>
        /// DefaultIncomingCallCompulsoryMessageUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultIncomingCallCompulsoryMessageUrl;

        /// <summary>
        /// TextBoxDefaultIncomingCallCompulsoryMessageUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDefaultIncomingCallCompulsoryMessageUrl;

        /// <summary>
        /// hvIncomingCallCompulsoryMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer hvIncomingCallCompulsoryMessage;

        /// <summary>
        /// ddlIncomingCallUrlRepeatCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlIncomingCallUrlRepeatCount;

        /// <summary>
        /// LabelIncomingCallErrorAsterisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelIncomingCallErrorAsterisk;

        /// <summary>
        /// TextBoxIncomingCallUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxIncomingCallUrl;

        /// <summary>
        /// DefaultRepeatIncomingCallUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatIncomingCallUrl;

        /// <summary>
        /// TextBoxDefaultRepeatIncomingCallUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TextBoxDefaultRepeatIncomingCallUrl;

        /// <summary>
        /// DefaultIncomingCallUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultIncomingCallUrl;

        /// <summary>
        /// TextBoxDefaultIncomingCallUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDefaultIncomingCallUrl;

        /// <summary>
        /// hvIncomingCallMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer hvIncomingCallMessage;

        /// <summary>
        /// ddlSystemFaultUrlRepeatCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlSystemFaultUrlRepeatCount;

        /// <summary>
        /// LabelSystemFaultAsterisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelSystemFaultAsterisk;

        /// <summary>
        /// TextBoxSystemFaultUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxSystemFaultUrl;

        /// <summary>
        /// DefaultRepeatSystemFaultUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatSystemFaultUrl;

        /// <summary>
        /// TextBoxDefaultRepeatSystemFaultUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TextBoxDefaultRepeatSystemFaultUrl;

        /// <summary>
        /// DefaultSystemFaultUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultSystemFaultUrl;

        /// <summary>
        /// TextBoxDefaultSystemFaultUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDefaultSystemFaultUrl;

        /// <summary>
        /// hvSystemFaultMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer hvSystemFaultMessage;

        /// <summary>
        /// ddlDropCampaignIsNotAvailableRepeatCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlDropCampaignIsNotAvailableRepeatCount;

        /// <summary>
        /// LabelDropCampaignIsNotAvailableAsterisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelDropCampaignIsNotAvailableAsterisk;

        /// <summary>
        /// TextBoxDropCampaignIsNotAvailableUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDropCampaignIsNotAvailableUrl;

        /// <summary>
        /// DefaultRepeatDropCampaignIsNotAvailableUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatDropCampaignIsNotAvailableUrl;

        /// <summary>
        /// TextBoxDefaultRepeatDropCampaignIsNotAvailableUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TextBoxDefaultRepeatDropCampaignIsNotAvailableUrl;

        /// <summary>
        /// DefaultDropCampaignIsNotAvailableUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultDropCampaignIsNotAvailableUrl;

        /// <summary>
        /// TextBoxDefaultDropCampaignIsNotAvailableUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDefaultDropCampaignIsNotAvailableUrl;

        /// <summary>
        /// hvCampaignIsNotAvailable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer hvCampaignIsNotAvailable;

        /// <summary>
        /// ddlDropCallInterviewNotFoundRepeatCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlDropCallInterviewNotFoundRepeatCount;

        /// <summary>
        /// LabelDropCallInterviewNotFoundAsterisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelDropCallInterviewNotFoundAsterisk;

        /// <summary>
        /// TextBoxDropCallInterviewNotFoundUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDropCallInterviewNotFoundUrl;

        /// <summary>
        /// DefaultRepeatDropCallInterviewNotFoundUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatDropCallInterviewNotFoundUrl;

        /// <summary>
        /// TextBoxDefaultRepeatDropCallInterviewNotFoundUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TextBoxDefaultRepeatDropCallInterviewNotFoundUrl;

        /// <summary>
        /// DefaultDropCallInterviewNotFoundUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultDropCallInterviewNotFoundUrl;

        /// <summary>
        /// TextBoxDefaultDropCallInterviewNotFoundUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDefaultDropCallInterviewNotFoundUrl;

        /// <summary>
        /// hvDropCallInterviewNotFound control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer hvDropCallInterviewNotFound;

        /// <summary>
        /// ddlDropCallOutsideOfOperationHoursRepeatCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.DropDownList ddlDropCallOutsideOfOperationHoursRepeatCount;

        /// <summary>
        /// LabelDropCallOutsideOfOperationHoursAsterisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelDropCallOutsideOfOperationHoursAsterisk;

        /// <summary>
        /// TextBoxDropCallOutsideOfOperationHoursUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDropCallOutsideOfOperationHoursUrl;

        /// <summary>
        /// DefaultRepeatDropCallOutsideOfOperationHoursUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultRepeatDropCallOutsideOfOperationHoursUrl;

        /// <summary>
        /// TextBoxDefaultRepeatDropCallOutsideOfOperationHoursUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TextBoxDefaultRepeatDropCallOutsideOfOperationHoursUrl;

        /// <summary>
        /// DefaultDropCallOutsideOfOperationHoursUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell DefaultDropCallOutsideOfOperationHoursUrl;

        /// <summary>
        /// TextBoxDefaultDropCallOutsideOfOperationHoursUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.TextBox TextBoxDefaultDropCallOutsideOfOperationHoursUrl;

        /// <summary>
        /// hvDropCallOutsideOfOperationHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.Confirmit.HelpTextViewer hvDropCallOutsideOfOperationHours;
    }
}
