//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Supervisor.Resources {
    
    
    public partial class DisconnectOrDeactivateDialer {
        
        /// <summary>
        /// dialog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.Dialog dialog;
        
        /// <summary>
        /// DialerHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.Hint DialerHint;
        
        /// <summary>
        /// DialerState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.Hint DialerState;
        
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.Controls.Hint lblMessage;
        
        /// <summary>
        /// DisconnectAndDeactivateDialerRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow DisconnectAndDeactivateDialerRow;
        
        /// <summary>
        /// rbDisconnectAndDeactivateDialer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.RadioButton rbDisconnectAndDeactivateDialer;
        
        /// <summary>
        /// DeactivateDialerRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow DeactivateDialerRow;
        
        /// <summary>
        /// rbDeactivateDialer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.RadioButton rbDeactivateDialer;
        
        /// <summary>
        /// TerminateTasksLine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TerminateTasksLine;
        
        /// <summary>
        /// TerminateTasksRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TerminateTasksRow;
        
        /// <summary>
        /// cbTerminateTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::Confirmit.CATI.Supervisor.ServerControls.CheckBox cbTerminateTasks;
        
        /// <summary>
        /// lblTerminateTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTerminateTasks;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Confirmit.CATI.Supervisor.MasterPages.Main Master {
            get {
                return ((Confirmit.CATI.Supervisor.MasterPages.Main)(base.Master));
            }
        }
    }
}
