//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confirmit.CATI.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t enable dialer. It is not installed in the system..
        /// </summary>
        internal static string CantEnableDialerMessage {
            get {
                return ResourceManager.GetString("CantEnableDialerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified password is the same as the previous one..
        /// </summary>
        internal static string ChangeToSamePasswordIsForbidden {
            get {
                return ResourceManager.GetString("ChangeToSamePasswordIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;{0}&quot; is not supported by call list search..
        /// </summary>
        internal static string ColumnNotSupportedMessage {
            get {
                return ResourceManager.GetString("ColumnNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete this operation for the &apos;{0}&apos; schedule as this is the default.
        /// </summary>
        internal static string Error_TryToCopyDefaultSchedulingScriptIntoItself {
            get {
                return ResourceManager.GetString("Error_TryToCopyDefaultSchedulingScriptIntoItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while person automatic survey update..
        /// </summary>
        internal static string ErrorWhilePersonAutomaticSurveyUpdate {
            get {
                return ResourceManager.GetString("ErrorWhilePersonAutomaticSurveyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while person automatic survey update - survey not found..
        /// </summary>
        internal static string ErrorWhilePersonAutomaticSurveyUpdateSurveyNotFound {
            get {
                return ResourceManager.GetString("ErrorWhilePersonAutomaticSurveyUpdateSurveyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while person automatic survey update - wrong task choice..
        /// </summary>
        internal static string ErrorWhilePersonAutomaticSurveyUpdateWrongTaskChoice {
            get {
                return ResourceManager.GetString("ErrorWhilePersonAutomaticSurveyUpdateWrongTaskChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while person task choice mode update..
        /// </summary>
        internal static string ErrorWhilePersonTaskChoiceModeUpdate {
            get {
                return ResourceManager.GetString("ErrorWhilePersonTaskChoiceModeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        internal static string ExportCallHistoryCallCenterColumn {
            get {
                return ResourceManager.GetString("ExportCallHistoryCallCenterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date time;Survey ID;Survey Name;Interview ID;Interviewer ID;Interviewer Name;Telephone Number;Extended Status;Duration;Waiting time.
        /// </summary>
        internal static string ExportCallHistoryGeneralColumns {
            get {
                return ResourceManager.GetString("ExportCallHistoryGeneralColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name contained invalid symbols. They were replaced with whitespaces..
        /// </summary>
        internal static string GroupNameContainedInvalidSymbols {
            get {
                return ResourceManager.GetString("GroupNameContainedInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer description contained invalid symbols. They were replaced with whitespaces..
        /// </summary>
        internal static string InterviewerDescriptionContainedInvalidSymbols {
            get {
                return ResourceManager.GetString("InterviewerDescriptionContainedInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer location contained invalid symbols. They were replaced with whitespaces..
        /// </summary>
        internal static string InterviewerLocationContainedInvalidSymbols {
            get {
                return ResourceManager.GetString("InterviewerLocationContainedInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer description contained invalid symbols. They were replaced with whitespaces..
        /// </summary>
        internal static string InterviewerNameContainedInvalidSymbols {
            get {
                return ResourceManager.GetString("InterviewerNameContainedInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {0} is not supported..
        /// </summary>
        internal static string OperatorNotSupportedMessage {
            get {
                return ResourceManager.GetString("OperatorNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified password does not satisfy password complexity rules..
        /// </summary>
        internal static string PasswordDoesNotSatisfyRules {
            get {
                return ResourceManager.GetString("PasswordDoesNotSatisfyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified password is too short..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic survey was reset.&lt;br/&gt;.
        /// </summary>
        internal static string PersonImport_AutomaticSurveyWasReset {
            get {
                return ResourceManager.GetString("PersonImport_AutomaticSurveyWasReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic survey was set to &apos;{0}&apos;.&lt;br/&gt;.
        /// </summary>
        internal static string PersonImport_AutomaticSurveyWasSet {
            get {
                return ResourceManager.GetString("PersonImport_AutomaticSurveyWasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer &apos;{0}&apos; cannot be created, password cannot be empty..
        /// </summary>
        internal static string PersonImport_CreatePersonWithEmptyPassword {
            get {
                return ResourceManager.GetString("PersonImport_CreatePersonWithEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password, description and task choice mode for existent interviewer &apos;{0}&apos; were updated.&lt;br/&gt;.
        /// </summary>
        internal static string PersonImport_PersonPropertiesAndPasswordUpdated {
            get {
                return ResourceManager.GetString("PersonImport_PersonPropertiesAndPasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description and task choice mode for existent interviewer &apos;{0}&apos; were updated.&lt;br/&gt;.
        /// </summary>
        internal static string PersonImport_PersonPropertiesUpdated {
            get {
                return ResourceManager.GetString("PersonImport_PersonPropertiesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of interviewer &apos;{0}&apos; cannot be updated because it is empty.&lt;br/&gt;.
        /// </summary>
        internal static string PersonImport_UpdatePersonWithEmptyPassword {
            get {
                return ResourceManager.GetString("PersonImport_UpdatePersonWithEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CATI interviewer account “{0}” has been locked, this interviewer will not be able to log into CATI until their account is unlocked. 
        ///The interviewer can be unlocked from the interviewer list in the CATI Supervisor. 
        ///
        ///Best regards, 
        ///Forsta..
        /// </summary>
        internal static string PersonLockOutEmailBody {
            get {
                return ResourceManager.GetString("PersonLockOutEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forsta – CATI interviewer locked out .
        /// </summary>
        internal static string PersonLockOutEmailSubject {
            get {
                return ResourceManager.GetString("PersonLockOutEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 100 records may be selected for a review session. Please select 100 or less records and try again.
        ///  .
        /// </summary>
        internal static string SendToReviewLimitMessage {
            get {
                return ResourceManager.GetString("SendToReviewLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified task choice &apos;{0}&apos; is incorrect. &apos;Automatic&apos; mode will be used.
        /// </summary>
        internal static string SpecifiedTaskChoiceIsIncorrectAutomaticModeWillBeUsed {
            get {
                return ResourceManager.GetString("SpecifiedTaskChoiceIsIncorrectAutomaticModeWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey was restored.
        /// </summary>
        internal static string SurveyArchive_SurveyWasRestored {
            get {
                return ResourceManager.GetString("SurveyArchive_SurveyWasRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey was restored, but:\n\r{0}.
        /// </summary>
        internal static string SurveyArchive_SurveyWasRestoredWithWarn {
            get {
                return ResourceManager.GetString("SurveyArchive_SurveyWasRestoredWithWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling script was changed after last archiving..
        /// </summary>
        internal static string SurveyArchive_Warn_SchedulingScriptWasChanged {
            get {
                return ResourceManager.GetString("SurveyArchive_Warn_SchedulingScriptWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State group was changed after last archiving..
        /// </summary>
        internal static string SurveyArchive_Warn_StateGroupWasChanged {
            get {
                return ResourceManager.GetString("SurveyArchive_Warn_StateGroupWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task choice mode is not specified. Automatic mode will be used..
        /// </summary>
        internal static string TaskChoiceIsNotSpecifiedAutomaticModeWillBeUsed {
            get {
                return ResourceManager.GetString("TaskChoiceIsNotSpecifiedAutomaticModeWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in from another station..
        /// </summary>
        internal static string UserAlreadyLoggedInFromAnotherStation {
            get {
                return ResourceManager.GetString("UserAlreadyLoggedInFromAnotherStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable type {0} is not supported..
        /// </summary>
        internal static string VariableNotSupportedMessage {
            get {
                return ResourceManager.GetString("VariableNotSupportedMessage", resourceCulture);
            }
        }
    }
}
