using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.Services.ReplicationServiceImplementation;
using Confirmit.CATI.IntegrationTests.Framework.Tools;

using Microsoft.SqlServer.Management.Smo;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Confirmit.CATI.IntegrationTests.Framework;
using Confirmit.CATI.Core.DAL.Framework;
using System.Data;
using System.Linq;
using System;

namespace Confirmit.CATI.IntegrationTests.Tests.DatabaseTests
{
    [TestClass]
    public class AutoGeneratedNameTest
    {
        #region Initialize and Cleanup methods

        private readonly IntegrationTestingFramework _framework = IntegrationTestingFramework.Instance;
        private BackendTools _backendTools;

        private const string CheckConstraintQuery =
            "select name, object_name(parent_object_id) from sys.check_constraints  where is_system_named = 1";

        private const string ForeignKeyConstraintQuery =
            "select name, object_name(parent_object_id) from sys.foreign_keys where is_system_named = 1";

        private const string KeyConstraintQuery =
            "select name, object_name(parent_object_id) from sys.key_constraints where is_system_named = 1";

        private const string DefaultConstraintQuery =
            "select name, object_name(parent_object_id) from sys.default_constraints where is_system_named = 1";

        [TestInitialize]
        public void TestInitialize()
        {
            _framework.TestInitialize();
            _framework.BackendInitialize();
            _backendTools = new BackendTools(_framework);

            var surveySid = _backendTools.CreateSurvey("p123786");

            var c1 = new ReplicationColumnInfo { DataType = SqlDataType.Int, Id = 3, Name = "q1", QuotaIds = null };
            var c2 = new ReplicationColumnInfo { DataType = SqlDataType.Int, Id = 4, Name = "key", QuotaIds = null };
            var c3 = new ReplicationColumnInfo { DataType = SqlDataType.Int, Id = 32, Name = "CallAttemptCount", QuotaIds = null };
            var p1 = new ColumnInfo { DataType = SqlDataType.Int, Name = "responseid", };
            var p2 = new ColumnInfo { DataType = SqlDataType.Int, Name = "respid" };

            var t1 = new TableInfo { Name = "response0", ReplicationColumns = new[] { c1, c2 }, PrimaryKeyColumns = new[] { p1 } };
            var t2 = new TableInfo { Name = "respondent", ReplicationColumns = new[] { c3 }, PrimaryKeyColumns = new[] { p2 } };

            ServiceLocator.Resolve<IReplicationSchemaService>().UpdateSurveyReplicationScheme(surveySid, new[] { t1, t2 });
        }

        [TestCleanup]
        public void TestCleanup()
        {

            _framework.TestCleanup();
        }

        #endregion

        

        [TestMethod, Owner(@"FIRM\AlexanderL")]
        public void DeployDatabase_CheckThereAreNoAutoGeneratedNamesForCheckConstraint()
        {
            AssertAutoGeneratedNames(CheckConstraintQuery);
        }

        [TestMethod, Owner(@"FIRM\AlexanderL")]
        public void DeployDatabase_CheckThereAreNoAutoGeneratedNamesForForeignKeyConstraint()
        {
            AssertAutoGeneratedNames(ForeignKeyConstraintQuery);
        }

        [TestMethod, Owner(@"FIRM\AlexanderL")]
        public void DeployDatabase_CheckThereAreNoAutoGeneratedNamesForKeyConstraint()
        {
            AssertAutoGeneratedNames(KeyConstraintQuery);
        }

        [TestMethod, Owner(@"FIRM\AlexanderL")]
        public void DeployDatabase_CheckThereAreNoAutoGeneratedNamesForDefaultConstraint()
        {
            AssertAutoGeneratedNames(DefaultConstraintQuery);
        }

        private void AssertAutoGeneratedNames(string constraintQuery)
        {
            var dbEngine = new DatabaseEngine(_framework.DbEngine.ConnectionString);
            var resultTable = dbEngine.ExecuteDataTable<DataTable>(constraintQuery, CommandType.Text);

            var result = resultTable.Select().Select(x => new { ConstraintName = (string)x[0], TableName = (string)x[1] }).ToArray();

            Assert.AreEqual(0, result.Length, String.Join(Environment.NewLine, result.Select(x => String.Format("ConstraintName = {0}, TableName = {1}", x.ConstraintName, x.TableName))));
        }
    }
}
