//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confirmit.CATI.Supervisor.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Confirmit.CATI.Supervisor.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action type is not initialized..
        /// </summary>
        internal static string ActionNotInitializedMessage {
            get {
                return ResourceManager.GetString("ActionNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action parameter for action &apos;{0}&apos; is not specified..
        /// </summary>
        internal static string ActionParameterNotSpecifiedMessage {
            get {
                return ResourceManager.GetString("ActionParameterNotSpecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action parameter type for action &apos;{0}&apos; is not specified or is wrong..
        /// </summary>
        internal static string ActionParameterTypeNotSpecifiedMessage {
            get {
                return ResourceManager.GetString("ActionParameterTypeNotSpecifiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t disable dialer. It is not installed in the system..
        /// </summary>
        internal static string CantDisableDialerMessage {
            get {
                return ResourceManager.GetString("CantDisableDialerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get timeZone with ID {0}.
        /// </summary>
        internal static string CantGetTimeZoneMessage {
            get {
                return ResourceManager.GetString("CantGetTimeZoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse Action List from xml..
        /// </summary>
        internal static string CantParseActionListFromXmlMessage {
            get {
                return ResourceManager.GetString("CantParseActionListFromXmlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item should have specified color..
        /// </summary>
        internal static string ColorNotInitializedMessage {
            get {
                return ResourceManager.GetString("ColorNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add timezone..
        /// </summary>
        internal static string CouldNotAddTimezone {
            get {
                return ResourceManager.GetString("CouldNotAddTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete timezone..
        /// </summary>
        internal static string CouldNotDeleteTimezone {
            get {
                return ResourceManager.GetString("CouldNotDeleteTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date in not initialized..
        /// </summary>
        internal static string EndDateNotInitializedMessage {
            get {
                return ResourceManager.GetString("EndDateNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete this operation for the &quot;{0}&quot; status group as this is the default.
        /// </summary>
        internal static string Error_TryToCopyDefaultStatusGroupIntoItself {
            get {
                return ResourceManager.GetString("Error_TryToCopyDefaultStatusGroupIntoItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error accessing Confirmit web service..
        /// </summary>
        internal static string ErrorAccessingConfirmitWS {
            get {
                return ResourceManager.GetString("ErrorAccessingConfirmitWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - timezone not found..
        /// </summary>
        internal static string ErrorTimezoneNotFound {
            get {
                return ResourceManager.GetString("ErrorTimezoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while deleting {0} &apos;{1}&apos; (SID={2}, GARBAGE_SID={3})..
        /// </summary>
        internal static string ErrorWhileDeleting {
            get {
                return ResourceManager.GetString("ErrorWhileDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while restoring {0} &apos;{1}&apos; (SID={2}, GARBAGE_SID={3})..
        /// </summary>
        internal static string ErrorWhileRestoring {
            get {
                return ResourceManager.GetString("ErrorWhileRestoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to receive root instance for the company &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorWhileTryingToReceiveRootInstanceForTheCompany {
            get {
                return ResourceManager.GetString("ErrorWhileTryingToReceiveRootInstanceForTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current exclusion intersects with exclusion with identifier {0} in timezone {1}..
        /// </summary>
        internal static string ExclusionIntersectionMessage {
            get {
                return ResourceManager.GetString("ExclusionIntersectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only exclusion shift type is allowed for exclusion object..
        /// </summary>
        internal static string ExclusionTypeExceptionMessage {
            get {
                return ResourceManager.GetString("ExclusionTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State group with such name already exists..
        /// </summary>
        internal static string GroupNameExistMessage {
            get {
                return ResourceManager.GetString("GroupNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item identifier is not initialized..
        /// </summary>
        internal static string IdentifierNotInitializedMessage {
            get {
                return ResourceManager.GetString("IdentifierNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect timezone.
        /// </summary>
        internal static string IncorrectTimezone {
            get {
                return ResourceManager.GetString("IncorrectTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is less than zero or is greater than collection size..
        /// </summary>
        internal static string IndexOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize of Dialler failed with result {0}..
        /// </summary>
        internal static string InitializeDiallerFailedInternalMessage {
            get {
                return ResourceManager.GetString("InitializeDiallerFailedInternalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize of Dialler failed..
        /// </summary>
        internal static string InitializeDiallerFailedUserMessage {
            get {
                return ResourceManager.GetString("InitializeDiallerFailedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview with ID {0} not exists..
        /// </summary>
        internal static string InterviewWithIDNotExists {
            get {
                return ResourceManager.GetString("InterviewWithIDNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview with the specified ID not exsists.
        /// </summary>
        internal static string InterviewWithTheSpecifiedIDNotExsists {
            get {
                return ResourceManager.GetString("InterviewWithTheSpecifiedIDNotExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call&apos;s property {0} has invalid value &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCallPropertyValueExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidCallPropertyValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call state &apos;{0}&apos; is not valid for this action..
        /// </summary>
        internal static string InvalidCallStateExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidCallStateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t convert string &apos;{0}&apos; to GUID value..
        /// </summary>
        internal static string InvalidGuidStringMessage {
            get {
                return ResourceManager.GetString("InvalidGuidStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} identifier {1} is not valid..
        /// </summary>
        internal static string InvalidIdentifierExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidIdentifierExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is in invalid state..
        /// </summary>
        internal static string InvalidItemExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidItemExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey {0} is not supported - invalid dial mode {1}. Only predictive surveys are supported..
        /// </summary>
        internal static string InvalidSurveyDialModeExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidSurveyDialModeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid survey ID value..
        /// </summary>
        internal static string InvalidSurveyIdValue {
            get {
                return ResourceManager.GetString("InvalidSurveyIdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item can&apos;t be deleted because of incorrect data format..
        /// </summary>
        internal static string ItemCantBeDeleted {
            get {
                return ResourceManager.GetString("ItemCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item can&apos;t be restored because of incorrect data format..
        /// </summary>
        internal static string ItemCantBeRestored {
            get {
                return ResourceManager.GetString("ItemCantBeRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with identifier {0} was not found in the collection..
        /// </summary>
        internal static string ItemNotFoundMessage {
            get {
                return ResourceManager.GetString("ItemNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not initialized..
        /// </summary>
        internal static string ItemNotInitializedExceptionMessage {
            get {
                return ResourceManager.GetString("ItemNotInitializedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cannot be null..
        /// </summary>
        internal static string ItemNullExceptionMessage {
            get {
                return ResourceManager.GetString("ItemNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITS with ID = {0} not found.
        /// </summary>
        internal static string ITSNotFoundMessage {
            get {
                return ResourceManager.GetString("ITSNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item should have name..
        /// </summary>
        internal static string NameNotInitializedMessage {
            get {
                return ResourceManager.GetString("NameNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Dialler in the system..
        /// </summary>
        internal static string NoDiallerInSystem {
            get {
                return ResourceManager.GetString("NoDiallerInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no records in BvSite table..
        /// </summary>
        internal static string NoRecordsInBvSiteMessage {
            get {
                return ResourceManager.GetString("NoRecordsInBvSiteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value &apos;{0}&apos; couldn&apos;t be converted to action parameter type..
        /// </summary>
        internal static string ParameterValueCouldntBeConvertedMessage {
            get {
                return ResourceManager.GetString("ParameterValueCouldntBeConvertedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root {0} group not found..
        /// </summary>
        internal static string PersonsGroupNotFound {
            get {
                return ResourceManager.GetString("PersonsGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire not found..
        /// </summary>
        internal static string QuestionnaireNotFound {
            get {
                return ResourceManager.GetString("QuestionnaireNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota definition is not in sync with the database. Survey relaunch may resolve this issue..
        /// </summary>
        internal static string QuotaDefinitionIsNotInSyncWithTheDatabase {
            get {
                return ResourceManager.GetString("QuotaDefinitionIsNotInSyncWithTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove null value..
        /// </summary>
        internal static string RemovedItemCannotBeNullException {
            get {
                return ResourceManager.GetString("RemovedItemCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respondent.
        /// </summary>
        internal static string RespondentTimezoneName {
            get {
                return ResourceManager.GetString("RespondentTimezoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule {0} is used in &apos;Set next rule&apos; action of sub-rule {1}.{2}..
        /// </summary>
        internal static string RuleIsInUseMessage {
            get {
                return ResourceManager.GetString("RuleIsInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule or sub-rule number should be in format &quot;number&quot; or &quot;number.number&quot;..
        /// </summary>
        internal static string RuleNumberFormatExceptionMessage {
            get {
                return ResourceManager.GetString("RuleNumberFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current shift intersects with shift with identifier {0} in timezone {1}..
        /// </summary>
        internal static string ShiftIntersectionMessage {
            get {
                return ResourceManager.GetString("ShiftIntersectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift {0} is used in action &quot;{1}&quot; of sub-rule {2}..
        /// </summary>
        internal static string ShiftIsInUseInActionMessage {
            get {
                return ResourceManager.GetString("ShiftIsInUseInActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift type &apos;{0}&apos; is used in {1} with identifier {2}..
        /// </summary>
        internal static string ShiftTypeIsInUseMessage {
            get {
                return ResourceManager.GetString("ShiftTypeIsInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift type is not initialized..
        /// </summary>
        internal static string ShiftTypeNotInitializedMessage {
            get {
                return ResourceManager.GetString("ShiftTypeNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is greater than end date..
        /// </summary>
        internal static string StartDateGreaterEndDateMessage {
            get {
                return ResourceManager.GetString("StartDateGreaterEndDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date in not initialized..
        /// </summary>
        internal static string StartDateNotInitializedMessage {
            get {
                return ResourceManager.GetString("StartDateNotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-rule {0} is used in &apos;Go to&apos; action of sub-rule {1}..
        /// </summary>
        internal static string SubRuleIsInUseMessage {
            get {
                return ResourceManager.GetString("SubRuleIsInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey &apos;{0}&apos; can&apos;t be restored because of missing parent folder..
        /// </summary>
        internal static string SurveyCantBeRestored {
            get {
                return ResourceManager.GetString("SurveyCantBeRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of survey&apos;s parent folders has been deleted previously, so it can&apos;t be restored..
        /// </summary>
        internal static string SurveyCantBeRestored_Details {
            get {
                return ResourceManager.GetString("SurveyCantBeRestored_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey couldn&apos;t be converted to type IPtBvSurveyEx..
        /// </summary>
        internal static string SurveyConvertionExceptionMessage {
            get {
                return ResourceManager.GetString("SurveyConvertionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find task for SurveySID={0} and InterviewID={1}..
        /// </summary>
        internal static string TaskNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("TaskNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error occured while script launching. Script was not generated.
        /// </summary>
        internal static string TheErrorOccuredWhileScriptLaunchingScriptWasNotGenerated {
            get {
                return ResourceManager.GetString("TheErrorOccuredWhileScriptLaunchingScriptWasNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time specified is out of shifts of selected type..
        /// </summary>
        internal static string TimeSpecifiedIsOutOfShiftsOfSelectedType {
            get {
                return ResourceManager.GetString("TimeSpecifiedIsOutOfShiftsOfSelectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While filling up lite timezone collection exception occurs. Collection could be incomplete: {0}.
        /// </summary>
        internal static string TimezoneLiteFillingExceptionMessage {
            get {
                return ResourceManager.GetString("TimezoneLiteFillingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timezone does not exist in the list of timezones and is not Respondent timezone..
        /// </summary>
        internal static string TimezoneOutOfRangeException {
            get {
                return ResourceManager.GetString("TimezoneOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this state group..
        /// </summary>
        internal static string UnableDeleteStateGroupMessage {
            get {
                return ResourceManager.GetString("UnableDeleteStateGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to activate calls.
        ///
        ///Possible causes:
        ///- Time specified is out of shifts of selected type.
        ///- Extended status does not allow activation.
        ///
        ///No calls were activated..
        /// </summary>
        internal static string UnableToActivateCall {
            get {
                return ResourceManager.GetString("UnableToActivateCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete script..
        /// </summary>
        internal static string UnableToDeleteScript {
            get {
                return ResourceManager.GetString("UnableToDeleteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get dialler configuration..
        /// </summary>
        internal static string UnableToGetDiallerConfigurationMessage {
            get {
                return ResourceManager.GetString("UnableToGetDiallerConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to terminate task..
        /// </summary>
        internal static string UnableToTerminateTask {
            get {
                return ResourceManager.GetString("UnableToTerminateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to terminate the interviewer’s session. The interviewer has already logged out. Please refresh the page..
        /// </summary>
        internal static string UnableToTerminateTaskLoggedOut {
            get {
                return ResourceManager.GetString("UnableToTerminateTaskLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error during script deleting.
        /// </summary>
        internal static string UnexpectedErrorDuringScriptDeleting {
            get {
                return ResourceManager.GetString("UnexpectedErrorDuringScriptDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurs during filter deleting.
        /// </summary>
        internal static string UnexpectedErrorOccursDuringFilterDeleting {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccursDuringFilterDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action with identifier &apos;{0}&apos; doesn&apos;t belong to actions dictionary..
        /// </summary>
        internal static string UnrecognizedActionMessage {
            get {
                return ResourceManager.GetString("UnrecognizedActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no event handler attached to validation event..
        /// </summary>
        internal static string ValidationNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationNotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%Resources.CallListHeaderVariables%&gt;.
        /// </summary>
        internal static string VariablesResourceString {
            get {
                return ResourceManager.GetString("VariablesResourceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier {0} is equal to zero..
        /// </summary>
        internal static string ZeroIdentifierExceptionMessage {
            get {
                return ResourceManager.GetString("ZeroIdentifierExceptionMessage", resourceCulture);
            }
        }
    }
}
