using System;
using System.IO;

namespace DotNetXmlToAdocConverter
{
    public class ParametersParser
    {
        public const string HelpString =
            "\r\n" +
            "Usage:  DotNetXmlToAdocConverter.exe <input file> <output folder>\r\n\r\n" +
            "input file  - an xml help file autogenerated by .NET\r\n\r\n" +
            "output folder - path to output folder with asciidoc result file\r\n\r\n" +
            "\r\n";

        public string InputFile { get; }

        public string OutputFolder { get; }

        public ParametersParser(string[] args)
        {
            if (args.Length != 2)
            {
                throw new ArgumentException("Wrong count of arguments");
            }

            InputFile = args[0];

            if (!File.Exists(InputFile))
            {
                throw new ArgumentException("The input file doesn't exist");
            }

            OutputFolder = args[1];
        }
    }
}