using System;
using System.Linq;
using System.Net;
using System.ServiceModel.Channels;

using Confirmit.CATI.Common.WcfTools.MessageInterceptor;

namespace Confirmit.CATI.Common.WcfTools.CookieManager
{
    /// <summary>
    /// Intercepts WCF messages at a channel level and resends cookies received from the server back with the HTTP requests.
    /// </summary>
    /// <remarks>
    /// We have to use channel level to set cookies because other methods don't work when we have additional web requests
    /// to establish sessions: 
    /// - AllowCookies binding options starts to send cookies only from the second WCf method call 
    /// - MessageInspector works at the message dispatcher level, so it is unable to intercept messages generated by the channels.
    /// </remarks>
    public class CookieManager : ChannelMessageInterceptor
    {
        /// <summary>
        /// Gets the current instance of <see cref="CookieManager"/>.
        /// </summary>
        public static readonly CookieManager Instance = new CookieManager();

        private readonly CookieCollection sharedCookies = new CookieCollection();

        /// <summary>
        /// Initializes a new instance of the <see cref="CookieManager"/> class.
        /// </summary>
        private CookieManager()
        {
        }

        /// <summary>
        /// Called when outgoing Message is ready to be sent.
        /// Injects cookies previously received from the other party to the headers of <see cref="HttpRequestMessageProperty"/>
        /// of the <paramref name="message"/>.
        /// </summary>
        /// <param name="message">The message going to be sent.</param>
        public override void OnSend(ref Message message)
        {
            if (this.sharedCookies.Count > 0)
            {
                if (!message.Properties.ContainsKey(HttpRequestMessageProperty.Name))
                {
                    message.Properties.Add(HttpRequestMessageProperty.Name, new HttpRequestMessageProperty());
                }

                var httpRequest = (HttpRequestMessageProperty)message.Properties[HttpRequestMessageProperty.Name];
                var cookie = String.Join("; ", this.sharedCookies.Cast<Cookie>().Select(x => x.ToString()).ToArray());
                httpRequest.Headers.Add(HttpRequestHeader.Cookie, cookie);
            }
        }

        /// <summary>
        /// Called when incoming message has been received.
        /// Saves the cookies contained in the the headers of <see cref="HttpRequestMessageProperty"/>
        /// of the <paramref name="message"/>.
        /// </summary>
        /// <param name="message">The message just received from the other party.</param>
        public override void OnReceive(ref Message message)
        {
            // Message could be null for one-way methods.
            if (message != null)
            {
                var httpResponse = message.Properties[HttpResponseMessageProperty.Name] as HttpResponseMessageProperty;

                if (httpResponse != null)
                {
                    Cookie cookie = ParseCookie(httpResponse.Headers[HttpResponseHeader.SetCookie]);
                    if (cookie != null)
                    {
                        sharedCookies.Add(cookie);
                    }
                }
            }
        }

        /// <summary>
        /// Clones this instance.
        /// </summary>
        /// <returns>Cloned instance.</returns>
        public override ChannelMessageInterceptor Clone()
        {
            return Instance;
        }

        /// <summary>
        /// Parses the string containing the cookie. Does not keep path or domain info in the cookie.
        /// </summary>
        /// <param name="cookieString">The cookie string.</param>
        /// <returns>Cookie if string is valid, null otherwise.</returns>
        private static Cookie ParseCookie(string cookieString)
        {
            if (string.IsNullOrEmpty(cookieString) == false)
            {
                // Remove all additional cookie info such as path or domain if exists in the string from the server.
                // Keep only actual name and value and store it in the parsedCookie array. 
                var parsedCookie = cookieString.Split(';').First().Split('=');
                if (parsedCookie.Count() == 2)
                {
                    return new Cookie(parsedCookie[0].Trim(), parsedCookie[1].Trim());
                }
            }

            return null;
        }
    }
}
