using System;
using System.Diagnostics;
using System.IO;
using System.Net;
using System.Windows.Forms;
using Confirmit.CATI.Installation.Common;
using Confirmit.CATI.Installation.Common.Interfaces;
using Confirmit.CATI.WindowsServiceTools;
using Confirmit.Security.Crypto;
using Microsoft.Win32;

namespace PrepareRestApiAdocHelp
{
    class Program
    {
        public const string HelpString =
@"
Usage:  PrepareRestApiAdocHelp.exe
This utility doesn't require any parameters but require Java JDK as a prerequisite.
You can install it from the following url: https://www.oracle.com/java/technologies/javase-jdk15-downloads.html.
This utility should be used to update CATI REST API adoc help files.
You can find these files in the following folder: Confirmit.CATI.REST.SDK\adoc\pages\RestApi.
Just run this utility from assemblies\Tools\ directory or use MSBuild\_updateRestSdkApiHelp.cmd file.

";

        public static int Main(string[] args)
        {
            if (args.Length == 1 &&
                (args[0] == "/?" || args[0] == "-?" || args[0] == "/help" ||
                 args[0] == "-help" || args[0] == "/h" || args[0] == "-h"))
            {
                Console.WriteLine(HelpString);
                return 1;
            }

            ILogger logger;
            try
            {
                logger = new FileAndConsoleLogger(Path.Combine(Application.StartupPath, "PrepareRestApiAdocHelp.txt"));
            }
            catch (Exception ex)
            {
                Console.WriteLine("Logging error:\r\n" + ex);
                return 1;
            }

            try
            {
                new Program().StartProgram(logger);

                return 0;
            }
            catch (Exception ex)
            {
                logger.WriteLog(true, ex.Message);

                logger.WriteLog("Global error:\r\n" + ex);
                return 1;
            }
        }

        private void StartProgram(ILogger logger)
        {
            logger.WriteLog(true, "Start an update of CATI REST API documentation");

            logger.WriteLog(true, "Set true for WebApi.EnableSwagger system setting for the first company");
            EnableSwagger(logger);

            logger.WriteLog(true, "Download json file with information about controllers generated by swagger");
            DownloadJson();

            logger.WriteLog(true, "Regenerate adoc files");
            GenerateAdocFiles(logger);

            logger.WriteLog(true, "Fix paths.adoc file");
            FixPathsAdocFile();

            logger.WriteLog(true, "Fix overview.adoc file ");
            FixOverviewAdocFile();

            logger.WriteLog(true, "Adoc files were updated successfully");
        }

        private void FixOverviewAdocFile()
        {
            string overviewStaticFile = @"..\..\Confirmit.CATI.REST.SDK\adoc\pages\RestApi\overview_static.adoc";
            string staticContent = File.ReadAllText(overviewStaticFile);

            string overviewFile = @"..\..\Confirmit.CATI.REST.SDK\adoc\pages\RestApi\overview.adoc";
            string content = File.ReadAllText(overviewFile);

            int startPos = content.IndexOf("__Host__", StringComparison.Ordinal);
            int endPos = content.IndexOf("\r\n", startPos, StringComparison.Ordinal);
            content = content.Substring(0, startPos) + content.Substring(endPos + 2);

            content = content.Replace(@"/catiapi/companies/1", @"/catiapi/companies/<CompanyId>");

            content = content + staticContent;

            File.WriteAllText(overviewFile, content);
        }

        /// <summary>
        /// Change something similar to &lt;&lt;_breakhistory,BreakHistory&gt;&gt; to link:definitions.html#_breakhistory[BreakHistory]
        /// </summary>
        private void FixPathsAdocFile()
        {
            string overviewFile = @"..\..\Confirmit.CATI.REST.SDK\adoc\pages\RestApi\paths.adoc";
            string content = File.ReadAllText(overviewFile);

            int startPos = content.IndexOf("<<", StringComparison.Ordinal);
            while (startPos > -1)
            {
                int endPos = content.IndexOf(">>", startPos, StringComparison.Ordinal);
                string[] parameters = content.Substring(startPos + 2, endPos - startPos - 2).Split(',');

                if (parameters.Length != 2)
                {
                    continue;
                }

                string newLink = $"link:definitions.html#{parameters[0]}[{parameters[1]}]";
                content = content.Substring(0, startPos) + newLink + content.Substring(endPos + 2);

                startPos = content.IndexOf("<<", StringComparison.Ordinal);
            }

            content = FixCallHistoryWithVariablesDescription(content);

            File.WriteAllText(overviewFile, content);
        }

        /// <summary>
        /// Remove from help file information about non existed /callhistorywithvariables('{NumberInOrder}') url and
        /// information about odata parameters for /callhistorywithvariables url
        /// </summary>
        /// <param name="content"></param>
        /// <returns></returns>
        private string FixCallHistoryWithVariablesDescription(string content)
        {
            int startPos = content.IndexOf("[[_callhistorywithvariables_getcallhistorywithvariablesbynumberinorder]]", StringComparison.Ordinal) - 4;
            int endPos = content.LastIndexOf("* CallHistoryWithVariables", StringComparison.Ordinal) + "* CallHistoryWithVariables".Length + 2;
            content = content.Substring(0, startPos) + content.Substring(endPos);

            int sectionStartPos = content.IndexOf("[[_callhistorywithvariables_getcallhistorywithvariables]]", StringComparison.Ordinal);
            startPos = content.IndexOf("|**Query**|**$filter** +", sectionStartPos, StringComparison.Ordinal);
            endPos = content.IndexOf("__optional__|Returns only the first n results.|integer (int32)", sectionStartPos, StringComparison.Ordinal) +
                     "__optional__|Returns only the first n results.|integer (int32)".Length + 2;
            content = content.Substring(0, startPos) + content.Substring(endPos);

            return content;
        }

        private void GenerateAdocFiles(ILogger logger)
        {
            string args = @"-jar ..\..\_3rdpart\swagger2markup\swagger2markup-cli-1.3.3.jar convert -i c:\Temp\v1.json -d ..\..\Confirmit.CATI.REST.SDK\adoc\pages\RestApi";
            logger.WriteLog($"Execute java {args}");

            using (var pProcess = new Process())
            {
                pProcess.StartInfo.FileName = "java";
                pProcess.StartInfo.Arguments = args; 
                pProcess.StartInfo.UseShellExecute = false;
                pProcess.StartInfo.RedirectStandardOutput = true;
                pProcess.StartInfo.RedirectStandardError = true;
                pProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
                pProcess.StartInfo.CreateNoWindow = true; //not display a windows
                pProcess.Start();

                string output = pProcess.StandardOutput.ReadToEnd(); //The output result
                string errors = pProcess.StandardError.ReadToEnd();
                logger.WriteLog(output);
                logger.WriteLog(errors);
                
                pProcess.WaitForExit();

                if (pProcess.ExitCode != 0)
                {
                    throw new Exception("swagger2markup utility failed. See PrepareRestApiAdocHelp.txt log file to details.");
                }
            }

            string fileToDelete = @"..\..\Confirmit.CATI.REST.SDK\adoc\pages\RestApi\security.adoc";
            if (File.Exists(fileToDelete))
            {
                File.Delete(fileToDelete);
            }
        }

        private void DownloadJson()
        {
            using (var client = new WebClient())
            {
                client.DownloadFile($"http://{Environment.MachineName}/catiapi/companies/1/swagger/docs/v1", @"c:\Temp\v1.json");
            }
        }

        private void EnableSwagger(ILogger logger)
        {
            string catiSqlServerName = GetCatiSqlServerName();
            string databaseName = "ConfirmitCATIV15_1";

            string catiConnectionString = $"Data Source={catiSqlServerName};User ID=sa;Password=firm";
            var dbEngine = new DatabaseEngine(catiConnectionString);

            string query = "EXEC [BvSpSystemSetting_Update] @SystemName = N'WebApi.EnableSwagger', @Value = N'True'";
            dbEngine.ExecuteNonQuery(databaseName, query);

            logger.WriteLog(true, "Restarting Confirmit.CATI.Backend.Rel$1 service to enable swagger.");
            WinServiceTools.StopService("Confirmit.CATI.Backend.Rel$1");

            WinServiceTools.StartService("Confirmit.CATI.Backend.Rel$1");
            logger.WriteLog(true, "The service was restarted.");
        }
      
        private string GetCatiSqlServerName()
        {
            string confirmitServerName;
            using (RegistryKey regKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\FIRM\ConFIRM"))
            {
                confirmitServerName = (string)regKey.GetValue("SQLServerName");
            }

            string encryptedConfirmitCredentials;
            using (RegistryKey regKey = Registry.LocalMachine.OpenSubKey(@"SOFTWARE\FIRM\ConFIRM\SqlSettings"))
            {
                encryptedConfirmitCredentials = (string)regKey.GetValue("SurveyC");
            }

            var confirmitCredentials = new CryptComp().Decrypt(encryptedConfirmitCredentials);

            string confirmConnectionString = $"Data Source={confirmitServerName};Database=confirm;{confirmitCredentials}";

            var dbEngine = new DatabaseEngine(confirmConnectionString);
            
            return dbEngine.ExecuteScalar<string>("SELECT [ConfigValue] FROM [confirm].[dbo].[CfgConfig] where ConfigId=623");
        }
    }
}
