using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Generated.Entity.Table;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.IntegrationTests.Framework.Tools;

namespace Confirmit.CATI.IntegrationTests.Framework.Data.Builders
{
    public class CallCenterDataBuilder : BaseObjectBuilder<CallCenterData>
    {
        public CallCenterDataBuilder(
            TestDataContext context,
            CallCenterData data,
            DataGenerator dataGenerator
            ) : base(context, data, dataGenerator)
        {
        }

        public override void Create()
        {
            CheckAndInitData();

            var entity = new BvCallCenterEntity
            {
                Name = Data.Name,
                LocalTimezoneId = 1,
                Description = Data.Description
            };

            ServiceLocator.Resolve<ICallCenterRepository>().Insert(entity);

            Context.CallCenters.Add( new CallCenterController(Data.Tag, entity.ID, Context));
        }

        public override void Setup()
        {
            if (Data.Dialer != null)
            {
                var controller = Context.GetCallCenter(Data.Tag);
                var dialer = Context.GetDialer(Data.Dialer);
                var service = ServiceLocator.Resolve<ICallCenterRepository>();
                var entity = controller.Model;
                entity.DialerId = dialer.Id;
                service.Update(entity);
            }
        }

        private void CheckAndInitData()
        {
            if (Data.Name == null)
            {
                Data.Name = DataGenerator.NewName(Data.Tag ?? "AutoGeneratedCallCenterName");
            }

            if (Data.Description == null)
            {
                Data.Description = "Call Center description";
            }
        }
    }
}