using System;
using System.Linq;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Generated.Entity.Table;
using Confirmit.CATI.Core.Repositories;
using Confirmit.CATI.Core.Repositories.Interfaces;
using Confirmit.CATI.Core.Services;
using Confirmit.CATI.Core.Services.PersonServiceImplementation;
using Confirmit.CATI.IntegrationTests.Framework.Tools;

namespace Confirmit.CATI.IntegrationTests.Framework.Data.Builders
{
    class PersonDataBuilder : BaseObjectBuilder<PersonData>
    {
        private PersonController _controller;

        public PersonDataBuilder(
            TestDataContext context,
            PersonData data,
            DataGenerator dataGenerator)
            : base(context, data, dataGenerator)
        {
        }

        public override void Create()
        {
            CheckAndInitData();

            CallCenterController callCenter = null;

            if (Data.CallCenter != null)
            {
                callCenter = Context.GetCallCenter(Data.CallCenter);
            }

            int callCenterId = (callCenter != null) ? callCenter.Id : CallCenterTools.DefaultId;

            var person = new BvPersonEntity
            {
                Name = Data.Name,
                ManualSelection = (int)Data.TaskChoice,
                Description = Data.Description,
                Location = Data.Location,
                FullName = "",
                CallCenterID = callCenterId,
                DialTypeId = (byte)Data.DialType,
                Type = (byte)Data.Type,
                AssignmentsListMode = (int) Data.AssignmentListMode
            };

            var personRepository = ServiceLocator.Resolve<IPersonRepository>();
            var id = personRepository.Insert(person);

            if (Data.AllowedChoices != null)
            {
                person.AllowedChoices = (int?)Data.AllowedChoices;

                if (person.PwdSetDate == DateTime.MinValue)
                    person.PwdSetDate = CallDeliveryService.NullTime;

                personRepository.Update(person);
            }

            if (Data.Password != null)
            {
                ServiceLocator.Resolve<IPasswordSaver>().Save(id, Data.Password);
            }

            _controller = new PersonController(Data.Tag, id, Context, Data);
            Context.Persons.Add(_controller);
        }

        private void CheckAndInitData()
        {
            if (Data.Name == null)
            {
                Data.Name = DataGenerator.NewName(Data.Tag ?? "AutoGeneratedPersonName");
            }
        }

        public override void Setup()
        {
            var groups = new[] { PersonGroupService.RootGroupId };

            if (Data.Memberships != null)
            {
                var groupTags = Data.Memberships.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                groups = Context.GetResources(groupTags).Select(x => x.Id).ToArray();
            }

            PersonService.SetParentGroups(_controller.Id, groups);

            if (Data.CallGroup != null)
            {
                _controller.Model.CallGroupID = Context.GetCallGroup(Data.CallGroup).Id;
                PersonRepository.Update(_controller.Model);
            }
        }
    }
}
