using System;
using System.Linq;
using Confirmit.CATI.Common.ServiceLocation;
using Confirmit.CATI.Core.DAL.Generated.Entity.Table;
using Confirmit.CATI.Core.Repositories;
using Confirmit.CATI.Core.ScheduleDom.Scheduling;
using Confirmit.CATI.Core.Services;
using Confirmit.CATI.IntegrationTests.Framework.Tools;

namespace Confirmit.CATI.IntegrationTests.Framework.Data.Builders
{
    class ScriptDataBuilder : BaseObjectBuilder<ScriptData>
    {
        public ScriptDataBuilder(TestDataContext context, ScriptData data, DataGenerator dataGenerator)
            : base(context, data, dataGenerator)
        {
        }

        public override void Create()
        {
            int scriptId;

            if (Data == ScriptData.DefaultSchedule)
            {
                scriptId = BackendTools.GetDefaultScheduleID();

                var scheduleService = ServiceLocator.Resolve<IScheduleService>();
                scheduleService.Launch(scriptId);
            }
            else if (Data == ScriptData.AllHours)
            {
                var schedule = ScheduleRepository.GetByName(Data.Name);

                if (schedule != null)
                {
                    scriptId = schedule.ScheduleID;
                    Context.Scripts.Add(new ScriptController(Data.Tag, scriptId, Context, Data));
                    return;
                }
                scriptId = InsertSchedule();
            }
            else
            {
                scriptId = InsertSchedule();
            }
            Context.Scripts.Add(new ScriptController(Data.Tag, scriptId, Context, Data));
        }

        public override void Setup()
        {
            BvScheduleEntity schedule;
            if (Data == ScriptData.AllHours)
            {
                schedule = ScheduleRepository.GetByName(Data.Name);
                if (!String.IsNullOrEmpty(schedule.XmlInUse))
                {
                    return;
                }
                schedule.XmlUnderDev = AllHoursSchedule.Xml;
            }
            else
            {
                ResolveScript(Data.Script);

                schedule = ScheduleRepository.GetByName(Data.Name);

                schedule.XmlUnderDev = Data.Script.GenerateXML();
            }

            ScheduleRepository.Update(schedule);

            ScheduleService.Launch(schedule.ScheduleID);
        }

        private void ResolveScript(TestScript script)
        {
            foreach (var rule in script.Rules)
            {
                foreach (var subrule in rule.SubRules)
                {
                    foreach (var action in subrule.Actions.Where(a => !String.IsNullOrWhiteSpace(a.Parameter.Constant)))
                    {
                        action.Parameter.Constant = BackendTools.Format(Context, action.Parameter.Constant);
                    }
                }
            }
        }

        private int InsertSchedule()
        {
            CheckAndInitData();

            var schedule = new BvScheduleEntity
            {
                Name = Data.Name,
            };
            return ScheduleRepository.Insert(schedule);
        }

        private void CheckAndInitData()
        {
            if (Data.Name == null)
            {
                Data.Name = DataGenerator.NewName(Data.Tag ?? "AutoGeneratedName");
            }
        }
    }
}
